In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.grid_search import GridSearchCV
from sklearn.cross_validation import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve
import math

%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
df=pd.read_csv("midterm_test.csv")

In [3]:
df.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
0,-0.522582,1.285266,-3.211278,6.435478,-3.355995,-6.222153,-4.668957,26.648275,-9.493768,-15.919583,...,6.597750,-0.197808,-4.138974,1.148979,0.127080,-0.032610,-39.456039,-0.623131,0.405111,0.565209
1,-0.327133,-2.874201,-8.628286,-4.543222,-0.687731,-0.306087,-12.544880,9.719749,-14.072453,3.763146,...,6.235120,-11.226443,-1.727902,2.983166,5.918433,-0.207522,-15.453140,-5.715456,2.596948,-13.330898
2,-0.173731,-11.401446,7.633143,7.298406,-5.554917,-17.192158,11.098016,-41.911009,12.719480,-7.320119,...,-13.414719,28.987108,-3.532879,0.806915,0.476301,0.154757,-63.918116,1.310607,0.609384,-21.962528
3,-0.130836,4.716583,-18.537297,-2.334537,-3.697804,-0.162074,-26.951837,-21.238950,3.145513,0.661810,...,2.890234,5.023080,-7.140230,0.208304,3.621499,-0.386714,-66.901730,-1.991627,1.363681,-1.916557
4,0.035572,-0.141469,7.792464,-4.398339,0.823660,-0.665133,11.329657,-12.837209,-5.064350,-3.699563,...,-8.381609,-2.068961,8.671673,1.373791,-1.182293,-0.110082,46.273615,2.625769,-3.100504,-1.482507

In [4]:
df.describe()

C:\Users\Rohit\Anaconda2\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
count,39993.000000,39995.000000,39990.000000,39993.000000,39994.000000,39989.000000,39991.000000,39987.000000,39994.000000,39986.000000,...,39992.000000,39993.000000,39985.000000,39992.000000,39997.000000,39996.000000,39993.000000,39996.000000,39995.000000,39987.000000
mean,0.001150,0.050029,-1.212748,0.037892,-0.017543,0.054597,-1.764113,-7.559937,0.077270,-0.022996,...,-2.215796,6.527137,-1.840976,0.007109,0.032597,0.003296,-12.681044,-0.023815,0.012795,-0.699512
std,0.370661,6.334603,13.244277,8.075404,6.366575,7.675792,19.256133,30.344781,8.904998,6.360036,...,16.910200,18.715717,5.128600,1.531295,4.137618,0.396432,36.737560,4.813593,1.938144,15.037603
min,-1.637195,-26.366592,-59.438295,-32.896394,-24.074707,-29.832100,-86.418814,-151.668029,-35.584361,-24.917306,...,-65.711291,-70.629012,-24.685394,-6.455841,-16.358976,-1.712737,-199.609887,-19.421488,-7.437804,-58.373259
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.697244,25.619887,51.047183,30.420903,24.241551,34.870000,74.218768,154.990430,40.395457,24.115795,...,75.263599,87.682808,22.140912,6.286530,16.679249,1.663191,131.577516,20.586126,7.781771,63.436061

In [5]:
df.isnull().T.any()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16        True
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
39970    False
39971     True
39972    False
39973    False
39974    False
39975    False
39976    False
39977    False
39978    False
39979    False
39980    False
39981    False
39982    False
39983    False
39984    False
39985    False
39986    False
39987    False
39988    False
39989    False
39990    False
39991    False
39992    False
39993    False
39994    False
39995    False
39996    False
39997    False
39998    False
39999    False
dtype: bool

In [6]:
df.isnull().T.any().T.sum()

392

In [7]:
nullrows = df[df.isnull().T.any().T]

In [8]:
nullrows

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
16,-0.080002,-3.996057,12.610601,2.699778,3.305612,14.143028,18.334866,5.918937,6.168532,4.562688,...,4.160472,0.728321,0.795320,-1.993936,-8.423694,-0.112500,-0.445456,8.485323,-0.620149,0.531935
31,0.359237,5.181104,-4.619430,0.382523,-8.476027,-0.413589,-6.716305,-4.276672,-1.528976,-1.759066,...,-5.058938,8.455196,3.646277,-0.651850,4.683005,-0.258369,43.731806,1.481998,3.191005,19.409465
165,0.284803,-11.256834,-14.417771,-1.716110,0.685712,-4.619654,NaN,6.515300,-3.014846,-13.638037,...,11.633417,10.658716,-9.480731,-2.459037,4.676046,-0.913933,-30.018290,-1.714813,0.748383,9.644043
176,-0.478195,-6.721827,-15.164784,3.914474,3.411644,16.045840,-22.048457,-18.692620,-14.678598,0.727056,...,-6.201832,-8.298007,NaN,-1.282679,-3.232978,-0.433443,24.970770,-1.490086,-0.459047,2.014385
202,-0.033666,3.619146,-17.619922,6.415630,4.800279,-0.067147,-25.618042,14.204170,19.893352,-7.089081,...,-10.748451,-28.938351,-3.390374,1.468866,-6.802180,-0.037301,-4.211652,0.753212,1.129832,NaN
396,0.450952,-1.014944,-12.299507,-9.603972,5.946021,4.388750,-17.882559,-22.772679,4.386124,-3.862643,...,-12.257402,4.404482,0.334554,-0.575795,-4.431077,0.826665,49.922964,-3.468746,3.074587,20.981209
415,-0.281347,9.139171,NaN,7.778547,4.591779,12.165179,-25.553870,-21.832722,13.387992,-1.292013,...,-1.099939,8.474707,-9.661455,1.009738,0.526828,0.207235,4.873831,1.999964,1.074500,23.227740
437,0.365192,3.879024,8.794182,2.775357,1.397091,10.866090,12.786080,-7.857713,15.561306,2.123218,...,NaN,11.898467,-1.470849,0.923427,-0.034080,-0.259296,-23.835802,-8.730397,0.758020,-9.320593
736,NaN,-0.972032,-7.497928,-8.889392,4.114729,8.708614,-10.901424,14.219227,2.365589,1.015814,...,-33.366429,-16.437833,5.415697,1.082095,-2.344104,-0.126789,60.227866,-1.341787,0.705265,34.863418
879,0.344249,9.574485,-6.190021,2.753796,-9.473160,-10.528537,-8.999825,17.315973,-16.564721,4.713151,...,1.489300,-2.952096,1.023792,NaN,-2.288455,-0.377789,-21.635364,4.115620,2.399953,2.032534
915,0.243587,0.422778,-4.977244,-3.100527,-4.228400,-1.962530,-7.236539,25.756475,3.626085,6.532468,...,-7.515479,6.977608,3.210521,-0.673406,-2.778612,0.000429,-1.316019,-4.439394,0.264013,6.576992
999,-0.195885,-0.035765,-0.881853,-2.887518,-0.154314,NaN,-1.282148,8.812764,12.067195,-2.884480,...,14.931662,-24.936085,-2.671063,-0.839371,-5.745191,0.170064,-22.798947,-7.045021,3.437089,-7.624105
1310,-0.075859,-2.285463,10.863891,NaN,-8.292225,-4.687446,15.795281,12.664676,-8.083606,-6.398938,...,10.176444,16.441359,-2.360155,-0.552888,-7.953337,0.261227,-37.702291,2.556598,-1.356776,3.769613
1340,0.622038,6.633118,8.923917,-4.185168,-2.310670,-8.268091,12.974705,18.460781,-4.533586,0.135697,...,-10.347192,-2.773545,-6.222872,0.443149,-3.104682,-0.188109,-70.443093,-1.638876,-2.507124,-6.766557
1343,-0.098895,-9.787568,15.570184,-9.214255,NaN,4.560004,22.637878,-3.596280,-6.007775,3.276035,...,7.222346,13.828448,-2.155318,-1.355745,4.071357,0.761838,8.745064,-3.215242,-1.527549,-13.696540
1378,-0.115419,-4.681605,12.695355,-7.348629,-0.079278,0.160307,18.458093,31.354944,8.076477,1.070894,...,49.777801,-7.106719,-12.742477,1.191400,-3.295520,0.403172,-68.336081,2.143319,-0.676070,-19.450313
1513,-0.220816,-4.479309,-6.228964,1.135547,1.994783,5.394194,-9.056446,16.575978,NaN,4.789265,...,2.916464,-4.644328,3.181024,-2.336496,-5.691226,-0.628596,71.019010,-1.738106,-0.675394,27.475799
1585,-0.200724,3.496516,13.112448,1.437191,2.066207,-3.774563,19.064513,17.586734,-3.428436,-1.871572,...,-29.387975,-7.679455,11.750468,-1.113054,2.429635,-0.027649,45.070472,-7.951429,-1.416602,8.577762
1722,0.319747,-0.933951,20.190411,-0.290101,-7.438682,1.293854,29.355341,15.017895,-3.228918,-12.972986,...,-15.641233,21.228092,7.583885,3.054190,6.113549,0.186999,30.377567,8.121702,-2.274548,NaN
1918,0.419066,-3.636151,11.095365,-2.577955,-2.572511,9.579378,16.131828,-3.778630,-2.901834,NaN,...,3.183800,30.428191,-2.172858,-2.019832,4.469712,-0.435477,-57.286254,9.262668,0.895697,-25.099952
1936,0.175956,4.636444,19.432836,-13.085454,-0.333705,9.426070,28.253884,-13.356717,1.675126,0.343967,...,-9.150360,54.896916,-1.941867,1.569607,-7.786803,-0.184338,-40.710323,0.322218,-0.072462,17.386879
2015,-0.038249,-0.877743,-19.808740,-4.236199,-3.396012,-8.591904,-28.800419,6.763685,-14.026173,-0.717467,...,2.427929,-2.053077,0.870493,-0.317869,1.920890,-0.167551,-35.335521,4.947797,0.856430,13.441787
2196,-0.070487,-1.496788,34.994061,-3.899176,9.547714,15.476633,50.878735,25.304283,14.105914,-4.192005,...,-7.095620,38.920598,12.974922,0.729538,-2.857260,0.249574,35.983944,4.257079,-2.495826,2.251346
2420,-0.271079,7.243872,3.436671,-4.545971,-0.261365,0.313259,4.996661,-20.948994,5.955006,12.078890,...,-28.914123,24.305257,4.911560,-0.088106,2.361412,-0.294250,6.942288,2.713970,-3.008085,6.890393
3167,-0.391979,-7.184145,-1.781373,-1.878833,-2.900312,-5.240312,-2.589982,-6.503297,-1.634455,13.615330,...,13.516146,6.497018,-5.137022,-0.163015,6.312364,0.156695,-43.681995,3.347096,-0.178374,-12.818719
3171,-0.408392,-7.838919,4.739126,2.685655,9.117706,-18.415246,6.890333,-13.399355,3.254762,1.249281,...,-3.349403,26.098471,NaN,-1.247016,-6.924580,-0.388766,35.028899,0.901137,3.746859,15.550707
3366,0.158671,2.241556,-7.217733,-6.091381,-3.028444,-9.893670,-10.494041,19.402994,5.114827,3.326509,...,6.341516,3.273868,-3.662761,2.259820,-3.577061,0.395470,-50.105374,-2.318385,2.083146,-2.054351
3401,0.510646,7.198395,-3.634364,3.958535,-0.281459,0.844115,-5.284091,11.722958,-11.992080,-4.101970,...,-15.885132,1.558302,2.740485,2.001171,4.297144,0.095295,6.837408,1.007176,0.912040,5.388758
3455,-0.300603,-8.586692,6.832009,3.501150,-6.412542,-1.798267,9.933228,-9.906652,2.131566,-17.644772,...,-19.035707,15.948457,-5.176117,0.541045,-0.062851,-0.167726,-24.570172,-4.379766,1.045613,10.209357
3846,0.636788,-2.017937,-17.150360,-23.949792,-4.233618,-10.853055,-24.935334,1.166430,0.462253,4.398373,...,-4.823369,7.185906,-3.146914,-1.502665,8.290276,-0.166109,7.966258,-4.151176,2.830554,24.870621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37350,-0.134016,-4.983000,-18.204059,5.738045,-6.488783,2.315014,-26.467334,NaN,2.156095,5.525126,...,1.733467,-33.732317,-0.982351,1.684834,-4.556148,-0.394960,32.812391,-9.130967,-3.055625,-8.337522
37491,-0.194734,8.573624,-18.024247,6.326774,2.317770,10.595451,-26.205901,-55.886295,-0.585232,-1.315948,...,-7.587005,-19.186316,-11.010940,0.629576,-0.200189,0.086244,-62.652716,-2.966775,-1.302574,-43.317537
37507,0.333743,4.428860,-16.067811,-6.335852,0.851062,0.950323,-23.361390,-23.336682,-9.564485,-3.533730,...,-21.678917,-6.501766,-1.496710,-0.321242,-3.218361,-0.064728,40.254117,-4.764640,2.473245,11.144925
37539,-0.133650,2.006979,-29.144478,-10.963297,4.541732,-3.157218,NaN,-7.026964,-6.842624,14.171947,...,-9.069540,-49.937088,2.309431,-0.592202,0.587729,-0.227854,14.768808,-4.335728,-2.181008,-13.643258
38201,0.215695,-5.114785,-4.842860,-12.121631,5.604151,-7.682133,NaN,2.793534,10.266495,-12.999253,...,-11.800502,5.042037,-2.861714,-1.638227,-1.482013,0.085768,11.263516,2.821537,1.618559,8.220548
38254,0.169951,9.067322,7.892055,9.955675,-0.657557,-3.311559,11.474455,13.214528,-1.259140,-5.526508,...,2.535128,0.233767,4.654305,0.521448,-6.628223,-0.166367,-26.129336,-4.184380,0.395415,-23.064054
38299,0.050317,1.513729,-22.523795,-6.740330,-0.969425,2.557195,-32.747905,NaN,4.792556,-3.080969,...,-2.187384,-35.432648,-8.079066,0.785497,8.404889,0.110897,-19.594427,2.587876,2.034431,-9.420024
38312,-0.316633,-12.179921,11.372892,-3.755091,-1.841710,-4.175120,16.535331,-12.060243,-10.906016,-3.785717,...,11.156116,13.476696,0.725219,-1.363330,3.921917,-0.056088,3.167410,4.213240,1.373437,-12.711046
38323,-0.133399,4.769523,-12.726008,7.306978,-1.365335,14.909126,-18.502659,-5.503482,-12.645671,4.245220,...,-14.415321,20.865546,2.001043,1.974082,-0.799089,0.175979,18.982570,0.736040,3.896299,27.032881
38393,0.536455,-10.358017,-8.466305,0.583202,7.571502,-12.930384,-12.309371,-5.734031,-13.109378,-7.480835,...,NaN,25.933854,-4.528673,1.400236,-0.552368,0.038201,-7.345895,-2.461669,3.906145,29.531204
38488,0.201322,1.405612,-3.391294,-0.957816,6.112124,-7.843528,-4.930687,-19.806895,-9.461451,-1.030489,...,-28.984816,9.078117,-5.356490,-3.654206,4.343765,0.052596,-39.982963,-2.995453,0.626146,14.507389
38505,0.140536,5.267820,5.656602,2.644636,1.808980,-1.779763,8.224274,24.594187,7.022540,-4.217975,...,8.438502,NaN,-3.553385,-1.614507,-7.949598,-0.244165,-55.382733,-5.042932,-1.991585,5.459969
38531,0.406583,10.549712,-25.578048,-3.873431,-7.794156,3.518787,-37.188560,-53.576898,0.851775,0.906573,...,-9.163942,-3.833670,-11.084360,0.943471,-1.543317,0.628823,-22.897230,-6.829338,0.410659,-6.583103
38539,-0.389646,-1.192508,NaN,1.231622,3.147114,-8.406682,-22.246409,17.291927,1.646378,-5.149631,...,-7.992546,-40.223100,2.887092,-0.221690,-5.839669,0.639712,20.248173,-5.930545,-3.519352,1.159441
38550,-0.152798,4.285643,19.473206,19.105427,4.383370,-4.692259,28.312579,NaN,-9.224439,2.893925,...,4.316480,0.307208,3.932957,-0.628700,0.033787,-0.535447,45.534291,4.202104,0.197837,-15.541277
38621,0.606461,-7.232815,23.572150,1.067426,-5.472911,0.336664,34.272136,36.172834,7.877672,4.528000,...,23.158065,-4.961802,-4.365679,1.410933,-7.215811,0.353163,-4.703892,-7.402957,-5.269785,5.206038
38786,0.135455,-3.753925,6.672305,1.548255,-7.289868,12.805711,9.701031,15.381297,-0.281964,-4.594284,...,4.181368,-4.019983,-4.283835,-0.911348,-5.379700,0.349283,-37.321137,0.416521,-4.326003,-6.257135
38822,-0.288094,6.976355,1.773391,3.198178,7.252081,17.415524,2.578377,3.324085,-11.270530,5.099987,...,-3.909617,-7.407281,-5.482348,0.174169,4.572799,-0.421095,-19.576564,-0.612247,-2.078476,-16.769272
38829,-0.135847,-8.702232,16.259209,-1.733463,-2.060558,-17.494272,23.639668,31.694563,3.952662,-0.505370,...,5.958506,19.996860,4.441465,0.709273,6.953686,0.215636,-41.529115,NaN,-0.912732,-12.335061
39014,0.086061,3.424943,4.933017,-6.400075,-8.534898,4.536570,7.172236,28.283140,10.448551,-10.186854,...,21.187469,-8.417032,6.130930,1.790779,4.463734,-0.300122,38.528571,2.594105,-1.444642,6.226538
39133,-0.095398,-9.697760,-5.329847,-0.011274,3.583647,1.431495,-7.749196,7.979487,1.994824,6.586985,...,9.633239,-0.553143,-0.797442,0.676613,-7.010775,NaN,-28.301166,5.229062,2.991915,-12.751381
39279,-0.101218,1.639239,-7.576006,-9.948372,-0.604395,-8.502899,-11.014943,-41.921044,3.756666,-1.670006,...,0.964210,46.308188,-7.896889,-0.845569,-1.383886,0.040769,-4.874788,-4.433117,1.727769,21.557810
39357,0.356304,-2.905859,-10.302410,0.842525,1.386817,0.768412,-14.978929,NaN,4.345279,-9.906718,...,0.302255,-26.344839,-5.287915,2.632178,-8.322795,-0.358727,-8.932827,0.104460,-2.553877,-11.210964
39404,-0.166766,4.587401,7.521360,-2.344792,11.455386,-1.165729,10.935492,-23.674310,4.240962,4.646901,...,-39.536518,44.502779,-1.617985,0.808826,-8.604663,-0.814029,-9.428321,-3.371395,1.581805,29.847837
39621,-0.037668,8.517376,-14.138185,3.584399,-3.430170,-3.423940,-20.555858,37.056394,16.836705,1.134064,...,13.760409,-2.783993,-3.348334,-0.375539,0.781745,0.308768,0.638239,5.883800,2.802261,16.323180
39640,0.191875,-8.772310,-19.069317,4.241129,-11.942379,NaN,-27.725354,32.945261,-0.171257,2.523920,...,16.907387,-12.997084,0.418163,1.030258,-4.038855,-0.328515,-26.812511,5.993732,2.734821,7.773823
39731,0.118695,-11.764550,5.692233,-26.293365,5.488238,-1.505307,8.276079,-38.949567,-17.221554,4.361646,...,-5.662953,15.461278,-7.200610,-0.246226,3.111564,0.022221,2.256452,-2.396175,-3.368245,1.350753
39758,0.020235,2.473674,-19.843408,7.046066,0.759135,3.646377,-28.850824,21.278827,-7.441848,5.757014,...,16.024274,-6.885164,-6.101892,-0.835804,-8.444453,-0.004981,-56.010010,4.758858,2.100242,15.335826
39906,0.248979,5.600473,-4.588263,2.711915,-0.896661,14.066456,-6.670989,3.827917,2.460980,-4.414807,...,-8.671471,-2.218692,-0.893659,1.179328,-0.890143,-0.637224,-25.711095,6.631830,-1.078175,3.648126
39971,-0.484285,-2.355493,0.426684,8.615683,6.953455,15.912097,0.620367,14.423536,-6.799821,-11.285372,...,-1.495509,-16.379263,9.678255,1.213855,5.518131,0.050803,50.942827,7.284607,-3.254093,7.000519

In [9]:
df.x0.value_counts()

-0.297201    1
 0.055615    1
-0.056813    1
-0.587128    1
-0.225062    1
 0.067805    1
-0.141105    1
 0.501502    1
 0.117110    1
-0.134728    1
 0.417888    1
-0.151998    1
 0.247180    1
-0.070858    1
-0.766266    1
-0.042246    1
 0.312202    1
-0.532647    1
 0.490303    1
 0.387029    1
 0.331749    1
-0.063778    1
 0.354024    1
 0.236518    1
-0.136811    1
 0.045901    1
 0.130437    1
-0.025346    1
 0.016609    1
 0.027348    1
            ..
 0.277591    1
 0.472349    1
 0.130139    1
 0.188110    1
-0.761910    1
 0.514400    1
 0.215783    1
 0.502710    1
 0.491636    1
 0.428894    1
-0.069762    1
-0.343846    1
 0.186027    1
-0.104902    1
-0.503138    1
 0.362882    1
 0.038689    1
-0.262290    1
-0.839907    1
-0.140012    1
-0.209302    1
-0.238912    1
 0.344150    1
 0.403922    1
 0.314471    1
-0.034575    1
 0.157389    1
-0.643592    1
 0.654092    1
 0.439498    1
Name: x0, dtype: int64

In [10]:
# Here is a simple function to show descriptive stats on the categorical variables
def describe_categorical(df):
    """
    Just like .describe(), but returns the results for
    categorical variables only.
    """
    from IPython.display import display, HTML
    display(HTML(df[df.columns[df.dtypes == "object"]].describe().to_html()))

In [11]:
describe_categorical(df)

In [12]:
df.x32.value_counts()

0.01%     10178
0.0%       8546
-0.01%     8354
-0.0%      7607
-0.02%     2600
0.02%      2030
-0.03%      406
0.03%       220
-0.04%       29
0.04%        17
-0.05%        3
Name: x32, dtype: int64

In [13]:
df.x37.value_counts()

$-881.11     4
$231.21      4
$-1406.76    3
$776.24      3
$533.53      3
$-142.68     3
$593.92      3
$487.98      3
$-579.24     3
$351.57      3
$-240.27     3
$-300.2      3
$-323.53     3
$-48.21      3
$352.65      3
$-349.97     3
$120.07      3
$488.91      3
$-326.74     3
$258.17      3
$718.5       3
$-1172.58    3
$-554.46     3
$459.41      3
$-327.49     3
$203.45      3
$-1244.41    3
$-433.69     3
$-794.8      3
$-49.33      3
            ..
$806.05      1
$-803.65     1
$806.07      1
$-190.37     1
$-631.71     1
$-1477.06    1
$1035.11     1
$-1200.89    1
$-1930.09    1
$263.54      1
$-1459.63    1
$-149.08     1
$-191.92     1
$240.22      1
$173.41      1
$-1039.29    1
$240.26      1
$2138.73     1
$283.49      1
$-610.17     1
$-787.79     1
$720.59      1
$-994.45     1
$-857.31     1
$1157.67     1
$-519.36     1
$-857.35     1
$720.51      1
$452.62      1
$284.99      1
Name: x37, dtype: int64

In [14]:
df[("x32")]=df["x32"].str.replace('%','')

In [15]:
df.x32=df.x32.astype(np.float64)

In [16]:
df[("x37")]=df["x37"].str.replace('$','')

In [17]:
df.x37=df.x37.astype(np.float64)

In [18]:
df.x0.isnull()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
39970    False
39971    False
39972    False
39973    False
39974    False
39975    False
39976    False
39977    False
39978    False
39979    False
39980    False
39981    False
39982    False
39983    False
39984    False
39985    False
39986    False
39987    False
39988    False
39989    False
39990    False
39991    False
39992    False
39993    False
39994    False
39995    False
39996    False
39997    False
39998    False
39999    False
Name: x0, dtype: bool

In [19]:
df[df.x0.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
736,NaN,-0.972032,-7.497928,-8.889392,4.114729,8.708614,-10.901424,14.219227,2.365589,1.015814,...,-33.366429,-16.437833,5.415697,1.082095,-2.344104,-0.126789,60.227866,-1.341787,0.705265,34.863418
4032,NaN,-13.278531,5.224180,8.031379,7.113948,-5.632316,7.595565,-76.814738,-4.694638,0.109942,...,2.279536,41.387411,-1.036445,1.235281,-6.257549,0.234067,46.315930,1.809038,3.355514,-3.179534
7341,NaN,-6.558542,2.574010,-5.177709,-0.575634,-4.037961,3.742417,13.571069,-4.025349,-3.841779,...,9.998477,19.228422,0.448871,-1.123461,-13.579642,-0.410003,-30.357167,-0.070304,3.427604,2.211305
9032,NaN,-1.363026,-14.511737,0.014416,2.383576,-8.438714,-21.098975,-21.175594,-13.332358,-7.076027,...,-10.474286,-0.586843,-1.690052,1.508175,1.888408,-0.268737,12.802009,-7.640010,0.374037,-0.366724
9252,NaN,3.873243,-14.970597,-1.280473,8.085783,10.393555,-21.766123,-44.365444,0.959803,0.636768,...,9.127374,16.152568,-3.637118,-0.610477,3.264251,0.198148,38.169067,5.052202,2.127707,13.958758
13338,NaN,1.514532,17.225170,-2.846814,8.971908,-7.671505,25.044102,40.794087,-3.598263,3.693619,...,29.167205,3.784944,-6.152614,-0.328858,-4.812709,0.123806,-40.772783,-2.244247,-1.888849,5.156692
19109,NaN,2.812956,-21.902109,7.118919,2.831426,21.085432,-31.844020,-47.480635,-10.711584,-3.334840,...,-25.676721,-16.657183,-5.709473,2.770588,1.125649,0.121068,50.866204,1.021700,-1.844232,1.877765

In [20]:
X0Mean = df['x0'].mean()

In [21]:
df['x0'] = df['x0'].fillna(X0Mean)

In [22]:
df[df.x0.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49]
Index: []

[0 rows x 50 columns]

In [23]:
df.x1.value_counts()

-0.857253     1
-0.366058     1
 4.685951     1
 3.780006     1
 0.331123     1
-2.433616     1
-2.997420     1
-1.075718     1
-0.197745     1
 8.710107     1
 0.941777     1
-2.961944     1
 3.628807     1
 3.604640     1
-10.251086    1
 5.685603     1
 8.688688     1
 9.405694     1
-3.988256     1
 5.722287     1
-4.188821     1
 2.636770     1
-1.202100     1
 4.950813     1
-5.656064     1
 0.892295     1
-5.719802     1
-1.673408     1
 6.747569     1
-1.781684     1
             ..
-2.953893     1
-5.833135     1
-4.582551     1
 7.008429     1
-6.386993     1
 1.664431     1
 2.701715     1
-0.227442     1
-5.832101     1
-5.583971     1
-0.015594     1
 9.360301     1
-1.863768     1
 7.791092     1
 4.283431     1
-3.870251     1
 6.717861     1
 0.285316     1
 5.136580     1
 0.076120     1
-4.316410     1
-8.776164     1
 7.547509     1
 7.789759     1
 6.884703     1
 3.919544     1
 0.221623     1
-6.067342     1
 7.880747     1
-8.373531     1
Name: x1, dtype: int64

In [24]:
df[df.x1.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
20332,0.126310,NaN,-8.563933,-2.515134,2.717837,-8.477928,-12.451316,6.796720,6.366925,9.354449,...,-1.141267,5.852421,-5.193545,-0.786251,-3.856710,0.405779,-65.223078,5.338836,1.849201,-14.048275
20529,-0.181611,NaN,11.860072,-4.410542,2.171256,1.299784,17.243653,-58.116897,-10.493606,-16.103197,...,-1.980662,27.803603,-10.751030,-2.055889,5.120102,-0.425251,44.678709,8.632443,-2.997645,5.341379
22711,0.441977,NaN,23.759041,4.215926,8.043510,-5.021445,34.543860,-78.287572,-1.260894,5.263387,...,0.264150,47.335073,-2.994769,0.854704,5.994847,-0.121764,24.502001,-4.620204,1.198617,-15.810419
29613,-0.083809,NaN,6.296154,10.058634,2.998616,1.214260,9.154135,8.872996,11.313783,-4.783383,...,1.070214,7.632306,-7.427971,0.627612,11.308343,-0.354596,-56.864593,7.672089,0.111893,-5.107785
31496,0.264798,NaN,10.350964,-1.817338,1.505715,13.306307,15.049523,31.505122,-7.148128,2.918496,...,-26.133718,25.532198,9.858147,0.164231,6.944259,-0.782561,-8.649886,-2.826344,-1.099757,6.005981

In [25]:
X1mean = df['x1'].mean()
df['x1'] = df['x1'].fillna(X1mean)

In [26]:
df[df.x2.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
415,-0.281347,9.139171,NaN,7.778547,4.591779,12.165179,-25.553870,-21.832722,13.387992,-1.292013,...,-1.099939,8.474707,-9.661455,1.009738,0.526828,0.207235,4.873831,1.999964,1.074500,23.227740
10140,0.060038,-13.164335,NaN,13.292428,1.989032,3.285533,-2.369386,0.379897,4.957606,-3.675466,...,15.806202,-6.906350,-12.003704,0.005486,7.900613,0.068374,-47.519559,0.611472,-0.964653,-14.827455
14224,-0.425291,11.100982,NaN,2.134705,3.678566,-8.945919,-12.981577,19.772466,17.119398,12.129679,...,-4.679759,6.408161,7.022290,-2.768817,3.244931,-0.073355,-53.050547,1.385831,0.923953,10.034637
20111,0.046841,3.211963,NaN,-4.930788,11.235641,0.179271,-5.303139,38.144786,-20.080546,-4.053326,...,41.994636,-20.906931,-14.235910,0.557003,-1.493242,-0.187910,-84.769091,-4.604911,3.118262,-41.019704
20659,0.136124,1.438192,NaN,4.344997,-1.607403,2.511820,-5.663818,11.797700,-1.219259,-0.519583,...,11.556260,20.993839,-1.560587,-0.037924,2.223114,0.255642,-13.606315,-4.134437,3.037198,8.852262
20765,0.260669,4.313479,NaN,7.661068,-2.515500,-3.885333,16.488739,48.913707,-3.506990,-3.273637,...,23.745549,-26.831694,4.842007,-2.039186,8.298262,-0.494763,-13.234423,-7.915595,-3.049231,-19.666104
25259,0.047007,7.014280,NaN,-1.805201,-3.864755,0.118907,-5.661635,25.701575,-2.913427,-4.036151,...,1.548292,-19.788576,5.521586,1.119163,1.955329,-0.313466,42.402696,-3.824891,-1.687574,6.029917
29322,0.346691,-7.101982,NaN,2.721478,-13.157116,-10.144180,-29.958448,-5.230743,2.196992,-0.566026,...,-11.404013,-1.705068,-5.291184,2.247111,1.856535,-0.289971,-26.812730,8.508516,1.956404,15.696522
36899,0.051459,-3.474105,NaN,-1.845708,-3.510317,8.812318,-41.573553,-79.761951,2.228146,-12.162295,...,-19.339715,0.339650,-16.322262,1.522137,1.203965,-0.308039,-50.524049,-1.963172,0.606311,-21.647874
38539,-0.389646,-1.192508,NaN,1.231622,3.147114,-8.406682,-22.246409,17.291927,1.646378,-5.149631,...,-7.992546,-40.223100,2.887092,-0.221690,-5.839669,0.639712,20.248173,-5.930545,-3.519352,1.159441

In [28]:
X2mean = df['x2'].mean()
df['x2'] = df['x2'].fillna(X2mean)

In [29]:
df[df.x3.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
1310,-0.075859,-2.285463,10.863891,NaN,-8.292225,-4.687446,15.795281,12.664676,-8.083606,-6.398938,...,10.176444,16.441359,-2.360155,-0.552888,-7.953337,0.261227,-37.702291,2.556598,-1.356776,3.769613
5103,0.112469,-0.241160,1.770020,NaN,-8.942266,-7.078008,2.573477,-10.416903,-5.009995,-1.376694,...,8.345868,7.933723,0.841368,2.424707,-2.570593,-0.321994,-34.140201,0.443255,-1.003690,-9.790028
17458,0.245405,4.970877,0.737685,NaN,-4.416025,2.537221,1.072539,10.580647,3.580006,8.484643,...,-0.470399,1.419994,-5.579700,-3.146625,-4.099805,0.044723,-65.566934,-10.967878,-1.281361,-6.613578
18268,0.415731,-6.229999,-19.042342,NaN,1.355958,-6.571637,-27.686134,22.136575,2.070840,-9.654888,...,5.969181,-9.700401,-4.546370,2.941898,8.926090,-0.429203,-78.498582,-10.963740,3.218757,-11.008607
23718,-0.374981,4.673685,-33.480636,NaN,3.932962,-15.039338,-48.678329,-34.737704,-2.257077,-4.009949,...,-14.158071,7.743758,-6.505935,-0.663043,-8.092276,0.216094,-22.681254,2.842452,3.221874,13.482950
31102,-0.050322,5.290148,22.499705,NaN,0.249161,3.763445,32.712880,4.352677,10.756324,-11.270299,...,20.094743,3.495898,4.774849,-0.963203,4.050921,-0.048057,7.413188,7.374277,-0.825438,-4.093279
32745,-0.517888,-7.004541,8.697329,NaN,-2.605085,-0.140760,12.645263,41.588548,2.030916,-1.259094,...,31.402677,-10.655500,-7.455721,-1.803925,-7.138427,-0.469402,-72.562478,-7.046058,-1.501139,-16.592852

In [30]:
X3mean = df['x3'].mean()
df['x3'] = df['x3'].fillna(X3mean)

In [31]:
df[df.x4.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
1343,-0.098895,-9.787568,15.570184,-9.214255,NaN,4.560004,22.637878,-3.596280,-6.007775,3.276035,...,7.222346,13.828448,-2.155318,-1.355745,4.071357,0.761838,8.745064,-3.215242,-1.527549,-13.696540
14972,-0.217645,1.406067,-19.546073,-10.220744,NaN,-8.414884,-28.418521,39.005732,-13.949897,2.640181,...,32.204876,-21.527089,-4.950250,-0.870920,10.411788,0.015952,-61.172454,-3.575895,1.658464,-3.886339
15297,-0.600524,5.312253,-24.084088,-0.490317,NaN,-1.906717,-35.016454,-76.721556,4.509264,1.809993,...,-39.832278,25.014610,-4.366024,-0.460566,-4.408931,-0.369525,-27.029526,6.852797,2.427984,10.255965
23639,-0.287635,-7.821805,-12.518418,3.526429,NaN,7.288764,-18.200839,-38.169390,-0.998978,9.592276,...,-25.354971,3.249985,-0.143269,0.518982,5.505384,-0.665510,16.036416,-4.308544,1.442072,4.020506
28335,-0.044110,4.761486,-3.727217,-11.001588,NaN,14.784465,-5.419094,-21.957176,13.358432,13.876793,...,-10.720510,-10.986337,0.112615,0.823328,7.943287,-0.429344,40.204200,0.684645,-3.936897,-3.016312
31618,0.010897,-1.013417,-17.372028,7.066908,NaN,6.159608,-25.257623,-17.679654,10.478312,12.097079,...,11.370731,1.907773,-6.732931,-0.458121,-4.843975,0.001170,0.301161,6.007977,-0.234939,29.493164

In [32]:
X4mean = df['x4'].mean()
df['x4'] = df['x4'].fillna(X4mean)

In [33]:
df[df.x5.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
999,-0.195885,-0.035765,-0.881853,-2.887518,-0.154314,NaN,-1.282148,8.812764,12.067195,-2.884480,...,14.931662,-24.936085,-2.671063,-0.839371,-5.745191,0.170064,-22.798947,-7.045021,3.437089,-7.624105
4599,-0.262081,-4.494074,-2.666405,-15.605539,9.839647,NaN,-3.876753,11.319435,-4.424167,2.520614,...,-2.662465,-11.902062,-3.993044,-0.409569,-0.237054,-0.187789,-22.535876,-1.777000,-1.112127,-13.483044
16654,-0.080399,9.552756,-15.282653,13.925082,-0.371814,NaN,-22.219829,-58.508603,-13.932190,7.853059,...,-8.708304,4.695031,-3.255164,-0.446932,-2.106894,-0.235114,41.365597,-4.282334,-0.151640,2.755787
18314,0.394598,-6.260232,-5.763177,5.366780,7.393260,NaN,-8.379227,3.836551,-7.077532,-6.214598,...,6.030710,-11.367218,1.796194,0.112379,1.708857,-0.458947,-3.106980,5.222083,2.634247,-6.721464
25786,-0.382975,-8.312322,10.533164,6.227776,-2.988576,NaN,15.314428,35.980554,7.628205,0.608413,...,26.563767,-10.939223,-3.793182,-0.212275,2.456883,0.204781,-90.243094,1.442710,-2.263557,-36.005238
25842,-0.480058,12.794324,8.858126,6.174946,-5.197749,NaN,12.879050,-7.515943,7.698629,11.514427,...,1.871583,-12.657478,-3.679351,-3.177763,2.358723,0.331292,-4.907478,1.653931,1.477867,-11.948220
30409,-0.456048,-13.846574,-2.474475,16.258280,5.406090,NaN,-3.597700,33.255725,-2.635617,-10.095652,...,-9.479686,-14.424021,-1.327511,1.859575,-8.985155,0.036534,-5.005259,5.813638,-2.912768,8.836962
31806,-0.181555,4.784894,-21.283525,9.178231,15.920569,NaN,-30.944646,-25.190602,-3.374767,-1.084604,...,-12.595715,-28.537293,-9.078151,-0.180899,6.067230,-0.330299,-29.511422,-2.356095,-0.592801,-21.643155
32406,-0.122988,2.349873,-3.911771,7.988291,-11.034849,NaN,-5.687421,-34.026484,-4.450517,-0.459943,...,6.293273,5.541136,-3.655404,1.950859,1.464255,0.461854,32.166890,-1.484430,-1.160422,25.752872
35132,0.642006,-5.208992,-16.896740,10.703025,-11.017682,NaN,-24.566590,-39.685430,8.804843,8.194421,...,-15.742952,-26.192961,-3.012458,-0.421212,0.848375,0.374236,45.880920,-3.609822,-3.755341,-6.268009
39640,0.191875,-8.772310,-19.069317,4.241129,-11.942379,NaN,-27.725354,32.945261,-0.171257,2.523920,...,16.907387,-12.997084,0.418163,1.030258,-4.038855,-0.328515,-26.812511,5.993732,2.734821,7.773823

In [34]:
X5mean = df['x5'].mean()
df['x5'] = df['x5'].fillna(X5mean)

In [35]:
df[df.x6.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
165,0.284803,-11.256834,-14.417771,-1.716110,0.685712,-4.619654,NaN,6.515300,-3.014846,-13.638037,...,11.633417,10.658716,-9.480731,-2.459037,4.676046,-0.913933,-30.018290,-1.714813,0.748383,9.644043
6094,-0.429002,-2.214127,4.393627,4.250147,5.439394,1.319879,NaN,11.334637,4.809765,0.948105,...,5.894654,37.105669,-0.049234,0.959022,-11.774651,0.011478,-12.687604,8.655706,-0.020831,21.381576
7508,0.149059,-7.265980,-20.682060,4.929705,-1.797157,3.199229,NaN,-61.318273,-5.951926,8.734317,...,-10.810314,-25.744038,-7.684558,0.792352,2.148353,0.000333,36.421269,-2.037164,-2.964066,-7.746356
10488,-0.030952,5.354561,-15.225265,5.685931,-2.062070,4.414658,NaN,-56.276928,-0.202835,-6.925547,...,9.529061,-3.808794,-5.012883,0.278554,-0.938233,-0.045465,15.653609,-12.820272,-0.846983,-8.296746
12332,0.416433,-3.628829,8.159928,4.311371,12.586975,-9.087339,NaN,-7.796791,11.012602,6.931730,...,-13.582826,5.610384,-5.469636,0.917402,4.472762,0.301242,-33.230136,0.199051,-0.375255,-8.501735
24797,-0.549271,8.633338,0.209984,1.150044,2.124860,-7.537125,NaN,-16.851411,4.211594,-8.819307,...,-9.000267,13.517918,-1.690265,-3.161350,-2.383423,0.072070,-64.295542,-1.560819,1.693108,-13.453147
29574,0.068719,-6.245469,3.917780,-6.224298,6.886683,-7.571130,NaN,-27.120743,0.146376,-0.540279,...,18.586975,8.091989,-8.632195,-0.674688,2.247285,-0.034005,-26.877176,0.816826,-1.981794,-10.487073
37539,-0.133650,2.006979,-29.144478,-10.963297,4.541732,-3.157218,NaN,-7.026964,-6.842624,14.171947,...,-9.069540,-49.937088,2.309431,-0.592202,0.587729,-0.227854,14.768808,-4.335728,-2.181008,-13.643258
38201,0.215695,-5.114785,-4.842860,-12.121631,5.604151,-7.682133,NaN,2.793534,10.266495,-12.999253,...,-11.800502,5.042037,-2.861714,-1.638227,-1.482013,0.085768,11.263516,2.821537,1.618559,8.220548

In [36]:
X6mean = df['x6'].mean()
df['x6'] = df['x6'].fillna(X6mean)

In [37]:
df[df.x7.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
5762,-0.030060,4.687321,12.606834,-1.205163,2.359276,5.634135,18.329389,NaN,18.011543,10.567653,...,-12.334921,4.861646,5.783320,-2.712535,-5.991170,0.044187,-31.106406,-5.380104,-3.571954,1.913287
10576,0.352688,2.038311,-20.360585,1.395843,8.941733,1.232738,-29.602761,NaN,4.790149,0.281851,...,8.897050,-29.853239,-8.237492,0.779626,4.642899,0.460311,-60.434204,-2.222370,0.415055,-19.070197
14878,0.297107,1.929482,-20.629037,7.733238,-6.420567,1.744577,-29.993069,NaN,5.520975,7.981463,...,-16.882440,21.198529,-4.962243,1.286009,4.461467,-0.140683,-56.134067,-2.333241,2.266818,-6.788529
15634,-0.137590,10.125865,-23.292846,17.060573,12.818005,9.319007,-33.866047,NaN,3.692555,5.747954,...,3.522260,-8.706308,-8.497088,-0.289335,5.824840,0.492349,-55.671286,0.477235,1.032903,-4.567573
16788,-0.497786,-7.409492,0.333720,-10.427158,-0.872693,-0.938186,0.485204,NaN,4.029642,5.605271,...,13.633992,2.353020,-4.645784,0.394443,-1.238251,-0.263586,-55.919402,-1.991841,1.164282,-14.390725
21698,0.759620,-4.071087,15.700188,4.904029,3.263073,-5.488918,22.826893,NaN,-6.955974,-8.912310,...,-19.475197,21.463669,6.589506,1.717009,3.762568,-0.317812,52.750350,1.846867,-2.837081,-14.733738
30913,0.434823,8.951682,-22.778439,-2.419181,-6.194710,5.500209,-33.118139,NaN,-3.298119,-2.842093,...,17.905975,19.421519,-13.637678,0.842812,0.844384,0.075443,-3.556878,2.298307,-0.154485,29.642397
33638,-0.216914,-9.247273,-5.660076,-1.504319,-0.463543,10.542554,-8.229325,NaN,2.351109,-7.756553,...,-20.621478,1.425266,-9.321724,0.239840,1.395532,-0.153887,-61.837027,4.483826,-0.294362,-6.976027
33701,0.282481,1.591523,-16.916448,0.903530,7.747280,-3.205558,-24.595244,NaN,9.795881,4.240925,...,-20.113071,44.917661,-7.056353,1.215037,-10.101172,0.043988,-47.393897,-9.412632,1.464413,-8.372931
37350,-0.134016,-4.983000,-18.204059,5.738045,-6.488783,2.315014,-26.467334,NaN,2.156095,5.525126,...,1.733467,-33.732317,-0.982351,1.684834,-4.556148,-0.394960,32.812391,-9.130967,-3.055625,-8.337522
38299,0.050317,1.513729,-22.523795,-6.740330,-0.969425,2.557195,-32.747905,NaN,4.792556,-3.080969,...,-2.187384,-35.432648,-8.079066,0.785497,8.404889,0.110897,-19.594427,2.587876,2.034431,-9.420024
38550,-0.152798,4.285643,19.473206,19.105427,4.383370,-4.692259,28.312579,NaN,-9.224439,2.893925,...,4.316480,0.307208,3.932957,-0.628700,0.033787,-0.535447,45.534291,4.202104,0.197837,-15.541277
39357,0.356304,-2.905859,-10.302410,0.842525,1.386817,0.768412,-14.978929,NaN,4.345279,-9.906718,...,0.302255,-26.344839,-5.287915,2.632178,-8.322795,-0.358727,-8.932827,0.104460,-2.553877,-11.210964

In [39]:
X7mean = df['x7'].mean()
df['x7'] = df['x7'].fillna(X7mean)

In [40]:
df[df.x8.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
1513,-0.220816,-4.479309,-6.228964,1.135547,1.994783,5.394194,-9.056446,16.575978,NaN,4.789265,...,2.916464,-4.644328,3.181024,-2.336496,-5.691226,-0.628596,71.019010,-1.738106,-0.675394,27.475799
7878,0.016699,-7.787469,-7.291102,-2.329441,5.729340,7.570772,-10.600714,-12.121893,NaN,-5.704826,...,4.954133,2.005147,-2.643836,-1.588640,4.017991,-0.453391,-24.154821,1.185071,1.199650,-14.387979
12125,-0.038383,4.420146,-5.611746,3.768951,7.134734,9.911649,-8.159058,-16.683266,NaN,-7.417890,...,-6.465228,22.904947,-9.016854,-2.582466,7.556700,-0.178068,-23.552051,-3.820137,0.480900,10.511320
14044,0.180254,7.939731,-6.546722,-11.062877,-1.741122,6.890560,-9.518441,25.933957,NaN,1.353762,...,19.778364,-14.025181,-3.836592,0.877575,-1.444137,-0.489215,-21.461228,3.400644,-0.561515,-0.287286
28458,-0.010810,4.794334,2.592316,-1.941519,8.716290,-6.365390,3.769033,-16.220716,NaN,-0.845153,...,-16.096964,-13.707043,5.266791,0.835372,3.196972,0.356533,53.807533,-4.094877,-0.173310,-10.976816
29845,0.015691,-0.717717,3.673934,-6.194175,1.421316,4.533308,5.341623,25.537619,NaN,-1.508824,...,13.197114,-3.174513,0.364185,-1.704407,-7.886403,-0.583348,-26.004757,4.103076,0.053775,-6.847692

In [41]:
X8mean = df['x8'].mean()
df['x8'] = df['x8'].fillna(X8mean)

In [42]:
df[df.x9.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
1918,0.419066,-3.636151,11.095365,-2.577955,-2.572511,9.579378,16.131828,-3.778630,-2.901834,NaN,...,3.183800,30.428191,-2.172858,-2.019832,4.469712,-0.435477,-57.286254,9.262668,0.895697,-25.099952
5131,0.327903,6.255738,1.956020,-8.175377,-2.415909,0.813739,2.843906,-17.746243,-11.405729,NaN,...,-12.801778,9.154526,-5.178862,1.144715,6.714887,-0.686597,-22.450283,4.099749,-1.985152,2.189639
12361,-0.416024,13.417671,-9.909915,-5.456914,-5.212329,9.705712,-14.408271,24.843474,-9.434487,NaN,...,-11.068633,-28.171107,-1.181982,-0.662824,-5.664884,0.149085,26.488857,-7.568895,-2.651550,30.511134
14290,-0.295425,6.322759,11.163097,12.146363,0.911682,-4.706131,16.230304,22.897776,-3.482148,NaN,...,10.359256,9.902703,-7.338605,2.194873,1.917526,0.050343,-120.031926,1.052892,-0.086920,-28.381101
14404,0.604733,-1.105335,-14.594809,2.939466,3.805433,6.657076,-21.219755,-13.108148,-4.472960,NaN,...,3.324190,-22.371071,-1.968585,-0.534000,2.227993,0.162626,-28.370711,0.707720,-0.599349,-23.204299
19000,-0.557737,-1.532818,-18.473964,17.354805,3.400413,-15.622607,-26.859756,-5.565812,-7.933982,NaN,...,8.836467,13.426970,-2.780026,0.646106,5.307795,-0.683674,-39.212511,-10.063932,2.182897,13.303091
25908,0.079932,4.306644,-10.850887,-2.322893,5.614635,-3.548991,-15.776374,-89.446568,-1.355083,NaN,...,-19.193160,-15.597246,-12.821894,0.022950,0.395608,-0.408225,28.417561,9.443587,-5.014135,-20.994665
26548,0.607081,2.067745,-16.135276,-11.419835,0.916527,-16.935263,-23.459478,11.736364,4.528452,NaN,...,-13.511391,-4.700899,-6.622244,-2.243087,7.903360,0.257936,-77.655772,4.946638,2.317028,-3.335106
29350,-0.409457,-1.297863,15.197605,-8.061906,5.190760,-7.095357,22.096176,35.737693,7.200800,NaN,...,38.060350,11.150077,-6.989890,-1.042442,7.130668,0.212405,-71.942119,-6.071907,0.709440,-25.640371
29874,0.077235,-10.676129,-3.717709,11.375716,-0.080427,1.029120,-5.405270,-31.417094,-1.038324,NaN,...,18.334325,18.113138,-6.902163,0.897553,-1.178251,0.206650,-4.139285,-7.398091,0.531373,4.922926
30180,0.401502,13.446080,2.109443,4.097310,-4.172055,2.234473,3.066972,-7.017408,-8.155877,NaN,...,1.453528,2.263221,-0.334796,2.651436,7.364451,-0.355325,19.414512,3.404971,-1.959278,-4.110583
31249,0.557971,6.364264,-9.669349,4.675179,-0.173352,7.001848,-14.058507,-32.231990,-14.054436,NaN,...,-8.201361,-3.588277,-3.382266,-1.206180,6.271446,-0.370548,4.541830,6.967924,-1.033586,-10.563170
34441,-0.310011,6.243384,-17.562146,-10.584012,10.123367,-14.278531,-25.534041,-5.210780,2.970077,NaN,...,-9.383166,-6.620184,-3.016709,0.102014,-3.287368,0.263562,-19.350714,1.219289,3.240911,-2.319523
35472,0.553826,-13.670456,-22.969754,-11.397557,5.591814,5.813095,-33.396296,-24.205988,-11.442627,NaN,...,-21.374686,-13.319398,-3.988495,3.593646,-1.850958,0.181963,56.743464,-7.459635,-0.285092,14.084504

In [43]:
X9mean = df['x9'].mean()
df['x9'] = df['x9'].fillna(X9mean)

In [44]:
df[df.x10.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
915,0.243587,0.422778,-4.977244,-3.100527,-4.228400,-1.962530,-7.236539,25.756475,3.626085,6.532468,...,-7.515479,6.977608,3.210521,-0.673406,-2.778612,0.000429,-1.316019,-4.439394,0.264013,6.576992
1936,0.175956,4.636444,19.432836,-13.085454,-0.333705,9.426070,28.253884,-13.356717,1.675126,0.343967,...,-9.150360,54.896916,-1.941867,1.569607,-7.786803,-0.184338,-40.710323,0.322218,-0.072462,17.386879
4996,-0.001386,3.012566,3.139857,1.485852,15.781488,-4.206802,4.565115,4.320038,-16.741379,-0.182175,...,6.514835,17.883439,-7.975097,0.363615,-0.694397,0.345448,-62.447768,-4.519715,0.051602,-11.378332
11807,-0.311708,-3.452605,11.287602,11.323561,-2.359192,3.011422,16.411325,-2.371717,-7.997289,6.055187,...,6.231479,8.645654,2.039060,1.791543,3.128794,-0.362774,-1.377519,5.661409,1.481837,-9.383680
12087,0.266314,-7.399540,5.526983,10.228134,-2.684639,-5.620806,8.035818,0.380078,6.954943,1.294158,...,11.596570,37.966770,-2.343812,1.168202,0.187686,0.620424,-42.389597,0.148555,1.817309,7.634214
14725,-0.940682,12.816661,-17.469310,5.372038,-3.662710,24.571777,-25.399063,-42.085704,-20.062538,5.087044,...,7.051644,17.043782,-6.132802,-1.171467,-3.046950,1.136109,8.519786,-7.372743,2.394126,17.459189
23095,-0.015638,0.901160,-6.988786,12.847915,6.278792,-4.897683,-10.161170,35.071386,0.727535,-1.964230,...,14.620499,-10.484567,-1.141726,0.990439,3.644011,-0.181261,-26.194638,-1.116469,3.335558,-1.644874
23949,0.211560,-9.181003,-25.924382,-0.602044,-6.996890,-7.832659,-37.692103,24.129259,8.495655,-2.798511,...,9.048010,-15.062404,-6.733033,0.655792,0.465133,0.476336,-84.296697,0.359835,5.682816,-17.761561
27664,0.010040,0.310144,-6.328194,2.755916,-10.102775,15.812348,-9.200718,4.888378,-9.753877,-0.159572,...,-9.501492,5.390878,-3.147114,1.621957,0.005396,-0.068383,-35.210133,3.164726,1.419859,8.339935
29706,-0.195387,-6.501939,22.582575,-6.735697,-1.844094,11.101724,32.833367,-8.889164,12.609431,-4.816247,...,-13.142371,20.621072,-9.881076,2.679757,-4.030013,0.706541,-49.654995,-1.935619,-2.891419,-10.808742
30486,0.410943,-0.080657,-11.685270,-8.444863,-1.789994,2.604424,-16.989505,-9.931632,-8.816829,-1.999757,...,15.872485,-4.899400,-3.234927,1.321511,-5.747368,-0.219289,-31.950727,-1.691777,0.760576,-12.742481
36909,-0.361879,-6.705446,45.259565,12.145862,2.770222,-5.081059,65.804007,29.907147,7.820277,8.183865,...,15.024608,19.320596,1.542841,-0.896279,-0.155465,-0.298974,-7.293999,-0.264795,-2.485555,-6.268547

In [45]:
X10mean = df['x10'].mean()
df['x10'] = df['x10'].fillna(X10mean)

In [46]:
df[df.x11.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
4118,-0.507755,1.927502,-0.611174,3.149465,9.099251,3.599169,-0.888601,-27.606999,-0.206728,5.052721,...,-18.018100,24.869276,-4.030992,-0.623932,1.744621,0.285259,-18.969258,-3.015401,-1.631219,10.095109
6222,0.556259,1.876961,1.524273,-0.319820,9.349981,-4.533546,2.216179,-11.869309,-2.388552,7.649456,...,-9.625499,16.230551,-0.248706,-0.563110,-4.371976,0.095285,-32.217147,5.427469,0.867751,-2.062671
12112,-0.364796,12.151983,4.220665,-1.386722,5.236187,-2.264483,6.136530,0.881384,-16.287736,0.266362,...,15.259026,4.703887,-7.993231,-0.142241,0.757390,-0.392275,-28.227626,1.783190,-0.263529,-7.829284
13920,-0.058950,12.337329,20.050576,17.392250,9.076585,2.139929,29.152031,-4.992418,4.112492,9.656267,...,2.003680,37.347170,-1.001505,0.226657,-3.156353,-0.730496,-9.757505,-1.982033,-1.349439,19.530309
17563,-0.200958,-3.799917,16.249352,-0.659562,-1.995200,3.834120,23.625337,-2.782467,6.374360,10.088795,...,-0.804117,-25.782214,2.513451,1.768920,0.691948,0.554225,66.298848,1.827750,1.818450,-6.880805
20097,-0.087965,-6.147927,10.556928,-13.303939,3.328506,-0.205109,15.348980,18.915360,-11.219552,1.741094,...,6.923806,-1.443957,-8.927054,0.000036,-0.187947,-0.073568,-68.830753,6.206017,-0.969132,-21.720395
20378,0.533608,11.290331,-14.223775,2.610745,21.759081,9.171733,-20.680301,0.518574,8.143764,5.070665,...,-9.171089,-2.091354,-2.995648,0.373044,2.836671,-0.333030,-25.628712,8.949588,-1.059527,14.276623
27172,0.089366,4.495275,11.675174,3.295390,-2.998966,-6.225925,16.974826,-20.763425,-5.541078,10.263710,...,-12.814581,23.112565,2.864659,0.037215,7.238935,0.605558,-7.480595,0.807736,-2.091150,-7.103443
30126,-0.251005,4.260767,-2.411488,1.467423,4.732226,-5.165733,-3.506123,-3.529718,-10.378947,-4.086053,...,-1.018295,15.481351,-0.476187,1.708868,0.262510,-0.206982,8.864616,0.625188,0.737002,17.733822
31255,0.040851,10.777163,5.144420,6.125102,-7.058310,-4.035655,7.479600,-8.781729,2.022648,-3.908338,...,-7.163715,15.804935,5.598582,1.317047,-3.908921,-0.488647,49.780944,-2.479640,2.523424,12.361855
34680,-0.346234,-9.752719,-13.117489,-1.022892,-3.737083,-2.793041,-19.071844,-24.180295,7.464024,1.391111,...,16.805614,-3.389088,-7.619390,-0.064007,0.856748,-0.742138,-36.748637,3.202504,0.580355,-11.551075
39621,-0.037668,8.517376,-14.138185,3.584399,-3.430170,-3.423940,-20.555858,37.056394,16.836705,1.134064,...,13.760409,-2.783993,-3.348334,-0.375539,0.781745,0.308768,0.638239,5.883800,2.802261,16.323180

In [47]:
X11mean = df['x11'].mean()
df['x11'] = df['x11'].fillna(X11mean)

In [48]:
df[df.x12.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
31,0.359237,5.181104,-4.619430,0.382523,-8.476027,-0.413589,-6.716305,-4.276672,-1.528976,-1.759066,...,-5.058938,8.455196,3.646277,-0.651850,4.683005,-0.258369,43.731806,1.481998,3.191005,19.409465
1585,-0.200724,3.496516,13.112448,1.437191,2.066207,-3.774563,19.064513,17.586734,-3.428436,-1.871572,...,-29.387975,-7.679455,11.750468,-1.113054,2.429635,-0.027649,45.070472,-7.951429,-1.416602,8.577762
5986,-0.030226,7.776312,2.966708,4.774898,-6.723134,-1.991885,4.313370,-52.099077,-12.191077,-6.872606,...,-38.824117,12.074988,-6.038215,-0.081103,5.040024,0.216821,33.558152,12.875184,-1.867232,7.993057
13579,0.159104,-0.986270,-1.889895,2.503146,-3.585041,-7.953945,-2.747765,27.294574,-14.468997,-2.922642,...,8.825586,-17.714818,-1.537781,2.655911,8.473986,0.490150,-72.078024,2.591172,0.967673,-35.169734
16125,-0.174266,2.847768,8.614468,6.298551,-6.993038,-1.659935,12.524789,-65.447550,10.375636,-14.154174,...,-17.123708,47.117700,-9.658014,-0.847094,5.860088,0.085074,-11.996324,3.023289,-0.774228,4.435780
26691,-0.213530,-4.122062,-9.373428,-21.447482,-1.745503,-9.974280,-13.628261,-1.803963,3.896652,-7.982566,...,25.969700,4.969223,-1.542733,0.331430,-1.045323,0.343029,18.853308,4.650827,2.426061,11.910792
26986,-0.122460,5.363761,6.014353,-1.777627,-5.674012,2.460921,8.744417,15.688898,-7.052243,-2.692544,...,7.580803,-8.206513,0.771879,-0.128212,9.866125,-0.154761,17.424237,-3.139890,-1.018605,8.281689
28701,-0.441896,10.649721,1.546490,12.341487,1.312870,-6.755711,2.248481,9.365190,-10.203313,-7.784747,...,-20.698958,-1.272454,4.027709,1.556233,4.592548,-0.091716,3.189956,1.072131,-3.962520,18.978291
35700,0.402870,15.312947,-8.099315,-4.915916,2.810008,-4.331854,-11.775796,-0.981367,2.022878,-1.493340,...,-6.166131,10.966671,-2.884603,-0.000344,1.837099,-0.066760,8.523453,1.108291,1.685417,18.672302
36593,-0.374931,-3.617431,0.457180,-0.912569,-2.771143,8.739464,0.664705,-31.016481,-6.479051,-3.975636,...,-3.232612,9.810765,4.917396,-0.817153,-2.480671,-0.536236,39.387372,3.107688,-1.352525,-9.280498

In [49]:
X12mean = df['x12'].mean()
df['x12'] = df['x12'].fillna(X12mean)

In [50]:
df[df.x13.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
12678,0.329614,4.372870,32.804649,-14.374520,-8.321593,1.005158,47.695494,-40.354874,13.214156,-8.213383,...,20.837410,45.529980,-4.323644,-1.116555,-6.221849,-0.082398,34.164182,1.117126,-0.730227,-5.856071
14262,-0.317425,2.623215,5.300083,13.359463,-11.370100,8.467460,7.705922,42.726596,7.646544,-2.127347,...,19.725121,-36.315315,8.919766,0.578358,2.712955,-0.742926,35.886233,-1.439710,-4.427183,-3.964834
18700,-0.149984,-2.160745,-3.772169,-10.028442,5.721987,-5.811985,-5.484450,-44.431496,0.676809,1.420072,...,-22.426123,-5.088522,-4.990058,0.212077,-0.286089,0.173019,4.901634,0.413384,-1.080476,-14.018218
19166,-0.225292,2.915545,3.906286,-2.145621,8.535689,-1.589054,5.679447,0.385314,29.897578,-1.568330,...,-19.781915,11.751928,6.304384,1.061820,-2.218948,0.143363,-35.714414,1.550447,-3.134855,9.929139
20243,0.207160,8.689474,2.552431,6.179806,-1.430829,-6.639219,3.711043,-47.320949,8.405820,9.480080,...,-25.058845,47.365736,3.582542,0.602360,1.755638,-0.120596,-52.999927,-2.273525,2.124092,-1.191851
23760,-0.342074,-12.247971,-1.690626,-6.604177,-0.037451,9.696256,-2.458043,-36.041926,-4.340172,-2.079491,...,-4.837487,23.150332,-1.297378,2.258456,6.797072,-0.706215,23.911735,-6.168784,1.902464,13.842130
24770,-0.699893,11.830002,-18.131631,-8.337487,-17.589131,-7.188206,-26.362029,-30.068611,2.584371,4.345911,...,-31.962105,12.242962,-8.825438,1.554250,3.198004,0.206871,-69.185069,-8.105826,3.621365,9.654822

In [51]:
X13mean = df['x13'].mean()
df['x13'] = df['x13'].fillna(X13mean)

In [52]:
df[df.x14.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
13824,-0.022061,-18.679731,41.487333,-3.664695,-1.302771,-10.084952,60.319465,38.522862,-5.874521,1.733539,...,33.143755,16.439633,-6.903919,0.913996,0.584948,0.299422,-85.712209,5.001803,-2.073442,-41.725103
14395,0.020611,4.010357,-5.702681,-2.620831,7.943584,-1.348606,-8.291270,-17.517053,20.490897,-11.218889,...,-3.377541,7.959738,-6.795198,1.069312,3.168230,-0.387540,-55.940072,1.862969,0.738646,-19.410995
14396,-0.331554,-2.132506,27.261173,3.829777,-6.131377,-5.988865,39.635697,-8.909421,-6.321254,9.050093,...,5.778629,38.873908,4.562670,2.747061,-8.185483,-0.011176,40.066040,3.198004,-2.274320,7.096111
15636,-0.174264,-6.414656,-1.505362,-1.780140,-0.043663,1.814136,-2.188684,-19.408319,-14.338942,-3.234297,...,-11.122298,12.537522,-2.589399,1.446814,2.009011,0.307577,-30.629950,-2.270439,-1.650847,-10.988712
21856,-0.844414,7.311811,3.198490,-1.457047,-13.257978,0.899654,4.650364,-9.068794,5.728687,4.143940,...,-6.339876,-0.510738,-5.079541,-0.688926,1.157196,-0.387465,-43.929512,-7.989031,0.836312,0.441108
33109,0.090634,2.556637,13.155733,4.820176,15.723677,5.020386,19.127448,-8.879380,5.441869,-1.707967,...,-6.455267,18.966448,4.844931,-2.033797,5.640114,-0.035721,-6.473646,-2.985971,-2.717815,-20.929765
36959,0.835639,11.382504,-15.787057,-0.447418,-0.675751,29.000508,-22.953194,-21.276957,-4.231508,-7.677536,...,-10.995587,-31.421580,-5.198739,1.126475,2.738568,-0.487612,-42.618954,-3.129422,-1.895729,-34.800973

In [53]:
X14mean = df['x14'].mean()
df['x14'] = df['x14'].fillna(X14mean)

In [54]:
df[df.x15.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
3167,-0.391979,-7.184145,-1.781373,-1.878833,-2.900312,-5.240312,-2.589982,-6.503297,-1.634455,13.615330,...,13.516146,6.497018,-5.137022,-0.163015,6.312364,0.156695,-43.681995,3.347096,-0.178374,-12.818719
6771,0.002501,-0.898611,-3.377680,-7.722929,-10.074109,3.507379,-4.910892,-30.448679,-12.723457,-0.770306,...,20.459830,35.957081,0.071176,-0.810886,-0.220125,0.152359,10.610858,1.480634,0.770995,6.348285
7232,0.097146,5.307722,-7.290582,5.883521,4.530605,3.015965,-10.599958,-7.946611,-2.967396,-4.892183,...,16.315177,8.912697,-1.373788,-0.409645,1.972814,-0.307302,-22.739766,-4.483190,0.043050,-5.828917
9992,-0.046187,2.160868,-11.169235,2.361682,6.534862,2.039901,-16.239228,-4.034168,-1.549628,9.875631,...,21.519935,0.950706,-13.404313,0.136864,0.225202,-0.049342,-46.889810,2.004227,-0.787348,-6.852994
10546,0.581864,6.861644,3.794585,5.233924,0.570420,9.261728,5.517041,26.998609,11.447654,-5.676937,...,4.774289,9.778054,0.801012,-0.194231,-3.948390,0.206407,-27.112627,1.715174,1.108408,-7.496152
15569,-0.039274,7.102037,15.590300,6.128127,-9.061727,2.436375,22.667125,14.539085,-7.108624,-5.560714,...,36.768517,14.558976,-5.985456,-1.528867,-2.868752,0.005637,-39.836099,1.710167,2.269574,-12.371851
15919,0.536286,-4.339571,-6.506832,8.107498,-1.472256,-6.267603,-9.460445,-12.277951,6.190817,12.798253,...,-14.397784,1.831987,-4.870990,-0.262989,-1.477817,0.079619,-37.266783,4.555989,-0.662681,-5.308198
32753,-0.641969,4.070370,30.611268,4.396639,3.873061,-10.302057,44.506483,11.418785,8.761820,-0.399495,...,-2.881928,47.332193,12.063406,3.733828,4.480033,0.379627,25.886968,5.166865,-1.350038,6.839909
33054,-0.002377,4.413915,7.544312,-13.646417,-5.007683,-2.733088,10.968863,50.923986,7.571985,5.965526,...,36.073656,-5.416733,-4.135433,0.880330,-4.220798,-0.321581,-54.983444,-1.717809,0.733685,-2.395752
33270,0.299168,-3.540263,-7.741715,12.252876,8.094815,5.641605,-11.255872,-16.288767,7.721566,9.021659,...,-4.458799,3.646660,-7.208198,-1.614153,-7.122320,0.667048,-7.197543,-4.268650,-0.853432,4.760747
33280,-0.185096,16.486669,38.016375,-3.290253,1.423639,1.607160,55.272952,-12.129512,-7.177106,2.030319,...,-19.025343,19.060721,-4.003043,-0.249526,6.768496,0.585413,5.470895,-1.706740,-4.601538,2.415366
35446,0.098445,17.629420,-7.542701,3.652902,-8.809620,-5.968699,-10.966520,-56.439036,11.492273,-2.785923,...,-27.333358,15.109292,4.044827,1.737440,4.779426,0.004613,32.167109,2.191280,2.397587,4.542927

In [55]:
X15mean = df['x15'].mean()
df['x15'] = df['x15'].fillna(X15mean)

In [56]:
df[df.x16.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
11210,0.405934,-1.190076,9.227567,10.718136,4.433192,6.511550,13.416189,24.307188,16.214473,0.705273,...,26.465056,1.335016,-3.485217,-1.168239,1.122078,0.297164,-47.945920,4.257073,-1.836300,-13.629009
29444,0.412783,1.589673,9.575166,3.710953,-14.907504,0.775744,13.921572,1.979291,-5.820248,4.421402,...,-0.748151,1.983866,-3.593771,0.489554,8.158265,-0.234934,-35.715557,0.673551,0.143263,-12.012194
37199,0.420283,-2.258921,-4.338943,0.291089,-6.567998,7.438440,-6.308497,3.773350,8.601879,9.977172,...,-5.879488,5.378424,-6.199110,-1.434500,1.670087,0.013605,-92.151686,6.517521,1.304096,-20.159689

In [57]:
X16mean = df['x16'].mean()
df['x16'] = df['x16'].fillna(X16mean)

In [58]:
df[df.x17.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
11754,-0.627727,5.387064,-13.591008,5.856773,2.411782,0.397575,-19.760304,-24.535746,-7.606807,-1.070309,...,-19.664003,2.151710,-2.485144,2.165645,3.695864,0.222098,-30.581179,-2.819657,1.994904,3.522373
30846,-0.293601,-6.208726,-5.395273,-8.438582,-8.625993,5.382236,-7.844321,-62.265786,6.609479,-7.139379,...,-10.784307,32.266751,-9.074490,-1.050937,-5.602877,-0.111280,9.952032,-1.567427,1.706126,12.769068
37300,-0.614775,1.280671,0.624693,-5.466590,-6.459423,-2.388065,0.908257,-19.259004,-12.596056,-0.852915,...,-14.638792,19.794571,1.614848,0.153353,-3.076629,-0.217970,-35.394904,0.328912,2.603657,-0.165277
38621,0.606461,-7.232815,23.572150,1.067426,-5.472911,0.336664,34.272136,36.172834,7.877672,4.528000,...,23.158065,-4.961802,-4.365679,1.410933,-7.215811,0.353163,-4.703892,-7.402957,-5.269785,5.206038

In [59]:
X17mean = df['x17'].mean()
df['x17'] = df['x17'].fillna(X17mean)

In [60]:
df[df.x18.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
2420,-0.271079,7.243872,3.436671,-4.545971,-0.261365,0.313259,4.996661,-20.948994,5.955006,12.078890,...,-28.914123,24.305257,4.911560,-0.088106,2.361412,-0.294250,6.942288,2.713970,-3.008085,6.890393
3455,-0.300603,-8.586692,6.832009,3.501150,-6.412542,-1.798267,9.933228,-9.906652,2.131566,-17.644772,...,-19.035707,15.948457,-5.176117,0.541045,-0.062851,-0.167726,-24.570172,-4.379766,1.045613,10.209357
4537,1.190229,-5.370059,5.584394,-6.502739,6.883252,-8.190125,8.119289,-39.644995,12.638449,3.760866,...,-22.463166,37.395200,3.451149,-1.970380,3.486408,-0.353989,16.995462,2.674119,-0.109936,0.066536
4644,-0.282870,-1.886832,-3.784368,-6.208588,6.643175,-0.256372,-5.502187,-51.454164,5.196142,4.824704,...,26.563128,32.511609,-10.850963,0.209095,1.027673,0.053211,-9.548927,-0.118561,0.661489,7.175969
7032,0.070888,2.131377,-23.854690,-1.029999,-7.746778,-6.509183,-34.682927,22.231411,10.266453,3.735826,...,-2.516054,-29.935667,-1.933398,-0.533792,7.102174,-0.045402,-41.181943,-9.988518,2.579069,-1.777483
10954,0.978325,-5.658839,0.069591,-3.414883,1.761474,10.259736,0.101179,-5.558685,-9.741952,-1.800930,...,-3.894249,-19.548996,-4.358204,0.882457,-3.730374,0.501402,-14.522101,2.833733,1.243064,-8.732262
17935,-0.359462,9.286230,-6.381712,-1.909878,5.072875,-0.384847,-9.278530,2.852807,0.469237,-3.154661,...,-0.687704,-14.713747,-5.089287,-1.490811,-1.624987,0.190029,-9.362154,-2.385800,-0.094201,-10.091511
21458,-0.527734,1.674276,-18.829523,-4.970440,4.006123,4.465277,-27.376711,25.472867,-10.750581,8.279641,...,14.960652,-13.115472,0.557584,-0.955764,0.598996,0.308587,-30.044015,0.026206,3.947636,-4.854959
25567,0.716889,-4.115296,21.531195,-12.523640,2.211581,12.819613,31.304740,-15.371093,22.170661,-3.426079,...,-0.630943,20.227742,-2.459881,-0.315970,0.602020,-0.191518,-61.142107,-2.191452,-0.962852,-36.998298

In [61]:
X18mean = df['x18'].mean()
df['x18'] = df['x18'].fillna(X18mean)

In [62]:
df[df.x19.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
5700,0.030410,-1.752259,4.418410,-1.912498,1.332495,2.376350,6.424037,45.934899,-9.330415,2.323540,...,5.225593,3.556678,3.021604,0.405727,-1.237603,-0.898443,12.251343,12.654432,0.963931,9.392192
17706,0.430611,-5.855524,-14.428185,-0.937066,-0.826302,-4.256441,-20.977497,21.072308,5.594341,-0.250616,...,26.347188,-7.907569,-1.984054,-0.245204,1.704733,-0.621424,-17.208101,5.949426,3.042737,17.119240
21059,0.282182,-3.896360,-19.428923,-15.075480,6.088417,-2.363637,-28.248194,-43.186605,-0.805904,1.882641,...,-6.624461,-5.045136,-10.122609,-0.776264,-2.452079,0.385187,-0.767096,-5.716953,-0.915076,9.607302
22910,-0.626931,3.270945,12.270704,2.803566,-8.520138,5.768776,17.840682,11.291130,-13.814527,13.459109,...,12.841481,-4.950881,4.649973,0.384284,6.761210,0.535002,14.755007,-3.953667,-0.919954,-6.023985
30051,0.177291,7.234447,-22.434268,8.767124,3.717480,-3.165848,-32.617740,-15.349662,6.872689,-3.805856,...,24.751919,8.553899,-7.835133,2.343835,4.510884,-0.007031,-33.798220,-4.175529,3.273499,8.554151
36301,-0.277421,2.806241,-16.439112,-8.481233,-4.895948,-5.433318,-23.901233,-3.033852,6.292608,-2.405366,...,-12.901445,7.425000,-2.213376,-0.326736,5.913904,0.395560,-29.277492,-2.255108,2.043421,14.243845
38312,-0.316633,-12.179921,11.372892,-3.755091,-1.841710,-4.175120,16.535331,-12.060243,-10.906016,-3.785717,...,11.156116,13.476696,0.725219,-1.363330,3.921917,-0.056088,3.167410,4.213240,1.373437,-12.711046
38786,0.135455,-3.753925,6.672305,1.548255,-7.289868,12.805711,9.701031,15.381297,-0.281964,-4.594284,...,4.181368,-4.019983,-4.283835,-0.911348,-5.379700,0.349283,-37.321137,0.416521,-4.326003,-6.257135

In [63]:
X19mean = df['x19'].mean()
df['x19'] = df['x19'].fillna(X19mean)

In [64]:
df[df.x20.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
1340,0.622038,6.633118,8.923917,-4.185168,-2.310670,-8.268091,12.974705,18.460781,-4.533586,0.135697,...,-10.347192,-2.773545,-6.222872,0.443149,-3.104682,-0.188109,-70.443093,-1.638876,-2.507124,-6.766557
10038,-0.029565,-1.348424,6.024238,6.244706,-1.098204,-7.706126,8.758790,73.416810,-0.151899,-8.036189,...,12.750155,-21.851018,-6.149401,-1.082332,2.244933,0.220168,-88.247786,0.953561,-0.860775,-10.640470
11114,0.259625,0.635303,-0.655295,13.181141,2.718016,3.776823,-0.952750,-49.680017,-2.819279,-14.845908,...,-4.530839,39.691056,-2.852492,1.763486,-2.463745,-0.293484,3.081682,7.492411,1.070290,15.556725
23406,-0.447991,-3.277567,-16.173171,-6.626948,8.069517,-16.008400,-23.514576,-11.421254,0.889097,1.883468,...,-13.306126,-7.807284,-5.489371,0.586797,8.114841,-0.240668,-42.895977,2.089515,0.950376,6.295511
27056,-0.067619,-6.886950,-10.992261,0.044084,-8.655344,-3.312607,-15.981921,-10.400125,-5.101690,2.045132,...,-27.857229,-13.825718,-6.239296,-1.213668,-0.819522,-0.590039,-39.093169,-5.386171,-3.035703,2.021807

In [65]:
X20mean = df['x20'].mean()
df['x20'] = df['x20'].fillna(X20mean)

In [66]:
df[df.x21.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
396,0.450952,-1.014944,-12.299507,-9.603972,5.946021,4.388750,-17.882559,-22.772679,4.386124,-3.862643,...,-12.257402,4.404482,0.334554,-0.575795,-4.431077,0.826665,49.922964,-3.468746,3.074587,20.981209
2196,-0.070487,-1.496788,34.994061,-3.899176,9.547714,15.476633,50.878735,25.304283,14.105914,-4.192005,...,-7.095620,38.920598,12.974922,0.729538,-2.857260,0.249574,35.983944,4.257079,-2.495826,2.251346
4243,-0.013844,2.688516,18.088450,0.364477,-0.999510,5.993601,26.299247,12.455175,4.613616,-4.496637,...,4.130827,-21.629109,5.763118,2.317572,-1.957125,-0.404313,29.446541,-0.356994,-0.951916,-5.002305
4729,-0.298973,1.597704,-13.316744,-7.515078,8.569027,-2.669417,-19.361545,14.601514,-3.326695,-6.532839,...,10.630276,-24.662325,1.780627,-1.582203,-1.098749,-0.725761,-15.346891,0.447986,0.319667,0.809813
12096,0.362941,-5.308578,8.552234,-5.707076,7.427434,-1.187814,12.434305,-8.024224,-2.446793,-2.637367,...,17.589717,4.406354,-7.002848,-0.534417,-4.456840,0.086904,-34.024710,-2.179370,-0.517984,-14.569595
13171,0.242098,-11.342290,16.606145,7.126011,-1.454850,11.771072,24.144087,-15.755658,8.018601,-0.303660,...,8.589000,12.894527,2.461446,0.926797,-2.283846,0.231765,12.388280,1.390821,0.273974,-13.874389
20604,-0.223800,-3.939484,16.778829,-4.552352,0.294040,-2.877990,24.395156,-16.505041,-18.346489,-1.844877,...,-10.482552,2.168518,3.460144,0.706704,10.432735,-0.943692,38.481988,0.569533,-1.033361,-0.491391
34417,-0.249908,13.403527,0.716257,-1.966092,8.527622,-2.979871,1.041384,16.051830,-3.511204,-6.142226,...,-32.585196,-15.869065,1.011143,-1.599908,-3.594646,0.810853,0.719386,-1.069038,-0.251185,14.294891

In [67]:
X21mean = df['x21'].mean()
df['x21'] = df['x21'].fillna(X21mean)

In [68]:
df[df.x22.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
10840,-0.569378,-3.093714,4.558750,-0.863342,-9.879457,-0.554633,6.628080,-0.774577,-16.254093,2.419291,...,0.368898,19.259383,-5.125083,-0.061794,1.506402,1.035743,-78.528037,-10.515298,0.933640,-21.894592
35143,0.496952,6.690678,-7.722706,-10.304736,6.360421,-4.918670,-11.228234,23.912136,-7.001564,-2.419973,...,9.118225,-10.190029,1.056397,-0.695914,7.188299,-0.093632,9.970702,3.518855,0.994093,5.485691

In [69]:
X22mean = df['x22'].mean()
df['x22'] = df['x22'].fillna(X22mean)

In [70]:
df[df.x23.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
2015,-0.038249,-0.877743,-19.808740,-4.236199,-3.396012,-8.591904,-28.800419,6.763685,-14.026173,-0.717467,...,2.427929,-2.053077,0.870493,-0.317869,1.920890,-0.167551,-35.335521,4.947797,0.856430,13.441787
6093,0.503827,-5.146056,17.230354,-27.092965,1.657630,7.303901,25.051640,2.326036,3.535331,-3.215885,...,-20.089232,8.529258,13.415315,-0.102466,0.651692,0.921622,60.377799,4.654176,-3.814681,-1.086680
9257,0.232767,1.762331,-6.070098,-0.116969,1.594659,8.506302,-8.825466,4.179506,-3.470304,5.223963,...,15.496136,-25.918631,0.582590,-0.626145,2.809449,0.873986,26.075792,-10.143576,2.554552,0.345520
23658,-0.296476,-2.531530,0.081551,5.599023,3.621213,-5.809834,0.118570,-9.741964,6.186382,-1.254258,...,2.057366,-3.865727,-4.086694,1.058087,3.520149,-0.191531,-15.379751,5.317938,-0.724469,-16.750611
23996,-0.219087,-14.389077,1.396202,5.531312,-1.623736,-7.527766,2.029973,-103.024172,-7.321181,5.466072,...,-15.276060,52.867641,-4.210864,1.169315,6.554070,0.258508,42.847686,-8.785335,3.186471,3.785493
24965,-0.628663,-5.352721,14.647761,-0.217373,-4.596478,-3.642424,21.296745,-1.705030,10.203411,-0.341561,...,2.387428,45.296126,-1.134755,-3.017850,-8.635081,0.753093,2.469343,6.126573,2.915802,15.207091
38323,-0.133399,4.769523,-12.726008,7.306978,-1.365335,14.909126,-18.502659,-5.503482,-12.645671,4.245220,...,-14.415321,20.865546,2.001043,1.974082,-0.799089,0.175979,18.982570,0.736040,3.896299,27.032881

In [71]:
X23mean = df['x23'].mean()
df['x23'] = df['x23'].fillna(X23mean)

In [72]:
df[df.x24.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
8456,-0.342352,2.667318,3.873110,1.482400,3.561828,-5.915880,5.631211,12.855805,-4.398431,0.190922,...,7.543947,30.705070,0.905195,-1.371124,2.499105,-0.876744,-37.856162,-4.300274,2.027714,5.567378
11025,-0.264340,-9.713574,7.994386,-10.359330,-2.355211,-15.821183,11.623236,-21.673111,-12.693168,-4.670983,...,-10.935383,51.567199,0.216406,0.708909,-2.422249,0.104239,-25.073906,3.427782,2.578627,18.263051
13426,0.344002,9.412529,0.619967,9.322279,3.894047,3.592669,0.901386,40.427156,-1.664217,-2.148232,...,-10.026934,-22.550975,4.386407,1.625376,0.796571,-0.497506,13.062516,-2.896985,-2.287758,-5.230421
16973,-0.316353,-1.814830,18.369124,0.607995,-3.004121,-3.294357,26.707326,57.214530,-10.387882,1.399227,...,5.051410,-7.515726,3.148282,-0.153098,2.576237,0.093940,-0.556570,2.818698,-4.119933,-1.856262
19764,0.052960,9.890102,-4.063376,-12.274928,4.181374,10.271977,-5.907844,-51.436143,-13.156764,-1.577203,...,-1.504701,36.529938,-6.337128,2.120465,1.902124,0.016643,-5.964296,2.359077,0.545317,3.657805
22057,-0.070340,6.583933,-17.707719,-3.717476,6.762169,9.810508,-25.745693,-28.357446,-3.538197,4.505742,...,-13.794200,-10.336719,-2.330515,0.918956,-0.744753,-0.178523,31.948618,3.785778,-2.300448,7.169442
24666,-0.355614,-13.352978,-6.865927,6.990435,-0.587019,-2.818745,-9.982542,-43.444838,-10.513913,2.740684,...,-24.359566,16.111072,-3.790844,-0.379371,-1.860675,-0.091027,-42.334363,3.133860,-2.383172,-25.885486
28739,-0.370700,-5.787550,34.849037,1.617566,-3.387448,9.436376,50.667881,29.310483,-4.192665,0.772982,...,35.900887,39.362265,0.933354,-0.325298,-1.525055,-0.277963,-61.505406,-4.415267,-1.727759,-28.658816
30123,-0.236602,-13.337902,-11.145248,4.604903,-2.019173,-0.913939,-16.204353,-52.617343,-9.772357,-14.105186,...,-35.182582,20.155871,-7.188696,1.134409,3.336701,0.019675,-46.519524,-3.285301,-0.375467,1.958256
31069,0.136342,-10.666194,-23.010345,1.101788,-11.082963,17.483618,-33.455313,-10.181245,-20.093962,7.719674,...,3.908390,-0.166045,-2.753466,2.738154,7.836327,0.228758,-8.751114,5.165770,3.374835,-0.638589
31560,0.049220,4.324128,12.368762,6.789684,-6.683051,-2.195970,17.983251,13.010322,-1.637298,-2.431401,...,11.476823,26.322702,1.227758,2.064295,-4.690736,0.346367,-57.241785,-0.183960,1.902030,-6.959788
38531,0.406583,10.549712,-25.578048,-3.873431,-7.794156,3.518787,-37.188560,-53.576898,0.851775,0.906573,...,-9.163942,-3.833670,-11.084360,0.943471,-1.543317,0.628823,-22.897230,-6.829338,0.410659,-6.583103
39014,0.086061,3.424943,4.933017,-6.400075,-8.534898,4.536570,7.172236,28.283140,10.448551,-10.186854,...,21.187469,-8.417032,6.130930,1.790779,4.463734,-0.300122,38.528571,2.594105,-1.444642,6.226538

In [136]:
categorical_variables = ['x24']

for variable in categorical_variables:
    # Fill missing data with the word "Missing"
    df[variable].fillna("Missing", inplace=True)
    # Create array of dummies
    dummies = pd.get_dummies(df[variable], prefix=variable)
    # Update X to include dummies and drop the main variable
    df = pd.concat([df, dummies], axis=1)
    df.drop([variable], axis=1, inplace=True)

In [88]:
df[df.x25.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
6715,0.068382,-6.478443,6.574829,-5.323271,-1.528135,-3.090992,9.559308,53.673797,-0.228554,4.763392,...,27.532092,-34.424779,1.926665,-0.781086,-1.662163,-0.234880,-47.818827,13.331849,-2.226276,-26.298971
10611,0.424413,-7.990091,17.608246,-3.127814,1.213282,-8.537899,25.601067,40.751296,0.948770,-3.789426,...,14.418919,9.077154,2.386413,-0.773855,5.641532,0.766814,-23.000911,0.761546,1.504388,-30.416538
12235,-0.033239,0.667505,-11.774080,-15.895339,-6.712939,1.909170,-17.118628,-62.964741,0.530138,-6.083357,...,-23.313151,31.055372,-6.070937,-2.514559,-2.169112,-0.048672,-51.082661,3.485084,1.421594,-12.116759
17940,-0.343234,0.955045,-5.084431,-3.111627,-11.405829,8.361994,-7.392380,-8.463512,6.088943,-7.234365,...,-14.964560,4.836524,-6.578697,1.007321,-0.361645,-0.249732,-10.200191,9.143146,-2.976699,19.575619
22528,0.107613,-1.256745,19.061838,0.057310,-15.361802,2.637964,27.714481,-1.109245,-1.499978,-13.440703,...,-1.349122,29.250463,-2.561448,-0.320841,-2.279116,0.412279,-71.173690,-0.725117,-0.804379,-14.632095
26395,-0.120889,10.473926,-14.665822,-6.970473,-3.232103,-2.005340,-21.323004,-22.633642,8.055125,2.482502,...,9.101738,31.101828,2.259939,-0.873383,3.388564,0.881328,16.930397,-7.300624,2.755746,23.727886
27369,-0.420375,1.537649,6.902733,1.711047,6.366710,-14.491146,10.036055,51.714096,10.747861,-3.467306,...,17.769401,-17.159319,6.121604,-1.484319,-5.559579,-0.475655,2.765340,-4.600275,-1.921547,0.967877
34360,-0.268147,-7.878904,8.224980,-8.859775,0.849182,-0.619430,11.958503,-1.534790,-7.469449,7.959021,...,11.300223,22.391676,-1.268454,-1.309139,6.239688,-0.058908,-7.525695,-1.141113,1.552809,4.219193

In [89]:
X25mean = df['x25'].mean()
df['x25'] = df['x25'].fillna(X25mean)

In [90]:
df[df.x26.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
3401,0.510646,7.198395,-3.634364,3.958535,-0.281459,0.844115,-5.284091,11.722958,-11.992080,-4.101970,...,-15.885132,1.558302,2.740485,2.001171,4.297144,0.095295,6.837408,1.007176,0.912040,5.388758
3925,-0.725981,4.512792,4.138200,-5.635658,4.542154,1.008148,6.016631,-13.984739,-7.815392,-2.307298,...,0.323988,30.075036,-3.772979,-1.682393,8.193729,-0.133894,-16.496539,6.009195,0.641081,0.743607
4926,0.162428,2.694496,-3.829131,2.425652,2.047531,-0.721986,-5.567269,-13.528150,-1.685342,-1.811723,...,12.875502,11.756257,0.535084,-0.685166,0.190908,-0.314917,6.181194,2.344425,-1.989566,12.662408
8556,-0.725808,-5.577791,13.367156,-6.956806,-2.642564,-0.370838,19.434840,3.050879,18.626210,12.599986,...,-6.694539,31.879021,-0.724622,-1.359555,7.188824,-0.062509,-21.205343,-2.849452,0.647366,12.062275
22496,0.255408,-12.882297,1.141808,11.323045,1.799309,5.176986,1.660103,-0.985609,6.053425,-8.872068,...,-0.187530,-3.207814,-2.094291,-0.024919,-1.707550,0.218115,-18.690365,-4.481765,-0.659655,2.046086
27967,-0.074303,9.033470,-0.416977,4.575824,-2.377946,4.268954,-0.606254,-11.229229,15.247265,-2.121162,...,-7.397407,18.768178,-4.338310,0.068470,-2.692187,0.434043,-14.034834,2.455965,0.534597,13.725833
28000,0.435124,2.725893,-13.894941,16.346962,-3.972750,0.535127,-20.202201,-32.425580,-4.624758,-7.031950,...,1.370361,4.321398,-9.855781,0.712274,-0.549565,0.199001,-35.893550,7.812315,1.721703,-14.673767
29117,0.322806,-0.281127,1.788847,-10.968908,-3.528899,-14.011192,2.600850,48.083741,7.170421,-1.220298,...,39.214394,-0.054257,6.644998,-0.610643,2.134243,-0.132867,-8.534802,2.283593,2.462787,7.010138
29830,0.083579,-0.338157,-18.670309,5.031580,4.075050,-3.019267,-27.145227,-9.648663,-3.578540,-6.214405,...,-0.194960,-6.569765,-1.055368,-0.169426,-2.385280,-0.055261,-41.267347,5.826926,1.992261,-0.623548

In [91]:
X26mean = df['x26'].mean()
df['x26'] = df['x26'].fillna(X26mean)

In [92]:
df[df.x27.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
10906,0.095541,13.347353,-16.509528,0.791604,11.614604,-13.446477,-24.003612,-20.615223,-17.137454,-0.457953,...,-5.192118,-5.825911,-2.103970,-0.662273,4.453053,0.335945,-2.256022,-1.726857,0.256682,-5.383473
27541,0.021374,4.041344,-1.965097,14.172259,4.838945,-5.232777,-2.857103,28.091644,3.255179,10.846444,...,-6.741503,2.886291,7.339418,0.101718,-4.925510,-0.336025,-23.385883,-2.864138,-1.775180,18.624447
39279,-0.101218,1.639239,-7.576006,-9.948372,-0.604395,-8.502899,-11.014943,-41.921044,3.756666,-1.670006,...,0.964210,46.308188,-7.896889,-0.845569,-1.383886,0.040769,-4.874788,-4.433117,1.727769,21.557810

In [93]:
X27mean = df['x27'].mean()
df['x27'] = df['x27'].fillna(X27mean)

In [94]:
df[df.x28.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
4041,-0.147191,-3.401970,11.863438,5.787504,-4.592286,-12.275023,17.248548,-11.118178,5.125922,7.221000,...,0.255331,4.971486,1.928444,-0.206761,3.331860,-0.483862,-10.935375,1.553626,-0.276452,0.758379
10628,0.397640,-1.685655,-2.433507,3.175773,-6.197723,4.005249,-3.538136,24.604107,-5.293099,-1.265819,...,34.203491,-36.348360,1.316964,-0.736233,-0.307980,0.264443,-6.381870,-3.873059,0.595929,-19.402566
16444,-0.236983,-2.867722,17.780628,0.841800,2.167232,6.783471,25.851697,10.589483,8.415895,-5.634496,...,-0.265508,7.396316,-0.230635,1.804485,-7.912254,0.777303,-30.135025,-6.008860,-4.861824,5.821384
21566,0.021964,-4.153942,9.179034,-8.009178,-0.957253,-7.775770,13.345626,-19.086328,0.800305,-1.939029,...,-23.716257,22.983857,9.555819,-0.121112,-2.512965,0.071296,47.951876,1.581648,-3.661833,5.586966
27694,0.396960,3.058285,-4.261015,-1.924455,8.214727,4.820390,-6.195196,-5.724400,0.081325,5.806767,...,2.471888,1.937506,7.485912,-0.694023,1.399637,0.411900,27.953361,2.441135,1.185016,0.172995
30421,-0.025723,-3.202705,1.054350,-3.523103,18.652460,-12.366394,1.532946,-33.287060,-0.076774,-9.301880,...,2.030976,22.052277,-1.203390,2.283828,3.955997,-0.389338,-1.268480,-1.537672,2.985842,-4.932966
36072,-0.138661,-1.521098,-4.750475,8.836268,-10.897375,-6.394090,-6.906834,-15.559202,-6.271154,-4.437165,...,-15.286669,31.770586,-0.364037,2.223627,1.292932,0.647788,-5.209210,-8.462226,1.952737,30.747249
37507,0.333743,4.428860,-16.067811,-6.335852,0.851062,0.950323,-23.361390,-23.336682,-9.564485,-3.533730,...,-21.678917,-6.501766,-1.496710,-0.321242,-3.218361,-0.064728,40.254117,-4.764640,2.473245,11.144925
39906,0.248979,5.600473,-4.588263,2.711915,-0.896661,14.066456,-6.670989,3.827917,2.460980,-4.414807,...,-8.671471,-2.218692,-0.893659,1.179328,-0.890143,-0.637224,-25.711095,6.631830,-1.078175,3.648126

In [95]:
X28mean = df['x28'].mean()
df['x28'] = df['x28'].fillna(X28mean)

In [96]:
df[df.x29.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
3366,0.158671,2.241556,-7.217733,-6.091381,-3.028444,-9.893670,-10.494041,19.402994,5.114827,3.326509,...,6.341516,3.273868,-3.662761,2.259820,-3.577061,0.395470,-50.105374,-2.318385,2.083146,-2.054351
10139,-0.329893,-0.295085,-12.471996,-16.188176,1.556836,4.252614,-18.133345,-6.957715,1.731399,-6.163829,...,-1.167421,-3.333539,-6.773243,4.063652,5.931527,0.361545,8.222880,-0.500682,-1.790826,26.862244
12910,0.230693,-7.672588,-5.169023,-2.286546,11.255348,-0.011859,-7.515372,-16.527280,-14.513747,-8.023169,...,-26.087387,2.485783,-0.072352,1.445911,-2.396198,-0.485287,-0.610451,0.316522,0.925514,7.362916
15237,0.532175,2.944782,-6.338025,-2.758083,-7.970384,2.718849,-9.215013,31.816381,-2.315359,4.506806,...,-6.441993,-11.578820,2.328801,-0.695383,4.973639,-0.514157,-18.165708,11.337820,3.417398,9.014920
19207,0.021863,-3.693098,-10.026736,-1.630528,0.238487,5.064327,-14.578120,25.993032,-1.917482,-14.019099,...,11.505866,-16.917710,1.783575,3.529088,3.280951,0.569206,14.968834,-3.744906,0.922450,2.512385
32580,0.103035,-8.084254,-3.019710,5.006129,5.261214,-1.769436,-4.390431,8.396489,9.725519,6.352527,...,-1.370658,-21.731613,6.413256,0.948581,4.689196,-0.464232,43.867432,-0.390560,-2.429793,-2.563337
32686,-0.464900,-0.649557,3.805924,17.693048,-3.551078,11.526876,5.533527,6.527348,-1.316611,10.663882,...,-51.840168,-6.778544,10.995591,0.838345,8.326704,-0.546793,94.749606,4.488878,-4.732033,23.713675

In [137]:
categorical_variables = ['x29', 'x30']

for variable in categorical_variables:
    # Fill missing data with the word "Missing"
    df[variable].fillna("Missing", inplace=True)
    # Create array of dummies
    dummies = pd.get_dummies(df[variable], prefix=variable)
    # Update X to include dummies and drop the main variable
    df = pd.concat([df, dummies], axis=1)
    df.drop([variable], axis=1, inplace=True)

In [98]:
df[df.x31.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
5958,-0.008845,-1.299149,11.800839,-24.689555,2.445570,12.148328,17.157533,-41.134365,14.357180,-2.031234,...,-24.956637,44.718107,0.859997,-3.153083,2.688217,-0.406995,-13.032959,3.233471,-2.473106,-10.368204
18732,0.131690,3.843121,-10.361005,-10.516950,10.099745,-4.603630,-15.064123,18.295354,-3.117539,-1.412242,...,13.064712,-18.747428,-6.371571,-1.145851,-2.075051,0.189828,-8.389246,-5.135442,-1.639001,-11.296240
23613,0.163533,2.224102,-13.707206,1.211613,9.024596,-2.606909,-19.929248,-21.616121,13.291884,-0.527538,...,-10.543265,3.710429,-1.758813,0.081143,0.843427,-0.099188,-30.405554,-4.557377,2.675328,-6.756356

In [99]:
X31mean = df['x31'].mean()
df['x31'] = df['x31'].fillna(X31mean)

In [100]:
df[df.x32.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
4846,0.453431,4.714105,-6.470945,-5.678835,0.831611,3.339826,-9.408268,-4.854747,-13.342630,-4.260828,...,22.599170,-3.455515,-9.086401,-4.453728,-0.711013,0.274818,-8.936047,3.439791,0.716149,-3.087840
11830,0.404590,1.251339,-22.694039,12.515235,-2.600181,7.667935,-32.995427,-23.044713,7.510051,-7.497398,...,16.247324,-21.890977,-2.825766,-0.639112,-4.191655,-1.330118,-25.512200,0.561023,0.039261,-13.669217
13850,0.235048,4.045896,7.592605,2.706755,-5.665054,-5.154999,11.039078,-41.967765,6.873178,3.362360,...,-22.800754,38.776216,1.081199,1.237774,-1.782096,-0.087074,-11.229490,5.173542,-1.149966,-7.348673
15208,0.060111,-0.983374,-3.181857,-2.156008,-2.904567,11.788238,-4.626180,-33.941925,-18.958637,1.955892,...,-13.693790,-1.648521,-5.811486,-1.153516,1.066275,-0.486212,3.593683,-3.086178,-0.075387,-6.477302
17263,0.376623,3.274790,10.420384,-5.003055,7.680784,-8.420761,15.150456,12.218284,-8.238400,-3.974578,...,-13.897114,-1.902132,6.793872,1.260263,-5.426677,0.241405,40.531822,-7.318671,-0.784807,21.565081
20274,0.019656,-7.462598,-7.325215,-3.643747,4.850687,13.078772,-10.650312,-53.316009,11.856107,1.588147,...,-1.545641,28.986238,-5.813249,-2.692404,2.972016,0.421501,-51.829340,-6.933372,-0.640378,-18.109112
27616,0.147370,3.771509,0.422316,-0.224434,5.500911,-10.332606,0.614016,-73.403493,8.577695,-2.895962,...,1.497675,42.613240,-3.278550,-0.276373,-6.473415,0.411288,52.157391,1.671306,2.508322,6.956601
31788,0.030224,0.150887,14.765130,-4.782869,-0.576765,-6.740068,21.467390,-25.826579,-7.695916,0.400881,...,23.112358,20.459512,2.791633,1.187810,-10.734306,0.144060,53.802381,0.002042,1.202929,-7.665148
34031,0.133259,-5.912846,-10.330900,16.205101,-3.032434,-5.065565,-15.020353,-19.354926,-5.581785,2.054258,...,14.060863,-4.568530,-6.418353,-1.269091,3.049534,0.539617,-10.661428,-5.027604,0.650054,-1.648448
39758,0.020235,2.473674,-19.843408,7.046066,0.759135,3.646377,-28.850824,21.278827,-7.441848,5.757014,...,16.024274,-6.885164,-6.101892,-0.835804,-8.444453,-0.004981,-56.010010,4.758858,2.100242,15.335826

In [101]:
X32mean = df['x32'].mean()
df['x32'] = df['x32'].fillna(X32mean)

In [102]:
df[df.x33.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
7792,-0.385327,-5.571987,-1.084918,1.858725,-0.593554,-6.079209,-1.577389,-25.089364,-8.852895,-5.517610,...,-12.394614,7.845692,-8.791585,2.067802,-4.565440,-0.070695,-16.946994,5.076169,-1.704142,-10.448321
8978,-0.210587,-6.075748,-21.718005,9.604155,1.557129,1.295713,-31.576347,-73.887862,6.799189,-2.802416,...,-21.028150,0.065634,-8.370572,1.171849,3.310035,-0.316367,15.376599,-4.346942,-1.115753,-4.999921
10094,0.208098,-6.019309,14.327231,12.049646,-2.870404,-24.109432,20.830718,25.678232,7.079503,10.143771,...,7.713224,18.289593,1.467020,0.297429,-0.529738,0.063632,-32.203355,0.299518,-0.934842,-22.492333
11579,-0.110171,-7.118374,6.118473,10.656477,11.461480,18.101893,8.895800,20.306308,3.634174,3.677454,...,-3.003218,4.316874,-0.005324,-0.473130,-1.246463,0.360789,-28.170267,-1.557679,2.250714,1.055361
15264,-0.222156,-10.100399,-27.972383,-1.691324,8.590039,-4.459429,-40.669743,-89.900449,-11.836633,-5.975337,...,-25.342917,-1.335929,-9.922752,0.626002,-6.553781,-0.329311,29.640121,10.028473,-0.207758,-6.558953
23156,-1.003887,10.597844,36.957261,1.118092,-5.340065,1.045809,53.733080,-33.401183,12.179978,-1.486989,...,18.222914,30.793310,8.232625,0.295720,5.273682,-0.159737,67.196657,-10.342623,2.124763,-23.718675
24953,0.183207,5.035700,6.805942,8.080440,1.956734,-8.296084,9.895329,-29.185150,5.617397,-8.689802,...,-28.556770,30.095347,-1.831762,2.866576,0.611617,-0.107365,-48.371144,3.493611,-3.161309,-5.040772
31495,0.229889,-6.097267,-7.879351,3.357262,-0.339404,6.721150,-11.455985,-61.668798,14.754555,3.846914,...,-13.828797,22.153586,-4.870557,-1.241719,3.503892,0.017854,-29.438467,-6.351444,-1.761815,-3.120895
32252,0.094251,7.087277,-4.885639,1.134322,10.028733,-9.669198,-7.103352,-17.978284,-8.731193,2.339126,...,-10.940073,-11.794537,-2.400116,0.517569,-3.211612,0.326034,-10.075745,-10.348680,-2.504090,-20.058856
38822,-0.288094,6.976355,1.773391,3.198178,7.252081,17.415524,2.578377,3.324085,-11.270530,5.099987,...,-3.909617,-7.407281,-5.482348,0.174169,4.572799,-0.421095,-19.576564,-0.612247,-2.078476,-16.769272

In [103]:
X33mean = df['x33'].mean()
df['x33'] = df['x33'].fillna(X33mean)

In [104]:
df[df.x34.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
1378,-0.115419,-4.681605,12.695355,-7.348629,-0.079278,0.160307,18.458093,31.354944,8.076477,1.070894,...,49.777801,-7.106719,-12.742477,1.191400,-3.295520,0.403172,-68.336081,2.143319,-0.676070,-19.450313
15378,-0.076148,-0.682541,-2.810899,12.684622,-4.483683,-3.141411,-4.086836,23.851049,5.919195,6.503025,...,4.254328,-1.372819,-9.661712,1.743672,3.098252,-0.638158,-94.755014,0.492298,1.782334,-23.545982
24318,0.052218,2.698285,-4.527594,4.081496,3.663770,5.095514,-6.582782,1.069200,-13.022265,-8.636271,...,-18.156480,-15.989665,-4.444293,-1.380893,2.663306,0.353483,-15.408287,-1.910599,0.011974,6.488273
25831,-0.360716,-8.223608,5.507116,-17.841381,-2.595578,9.565147,8.006932,-47.546059,-6.117408,9.551198,...,-23.816054,5.342769,-4.502684,2.361406,-5.015196,0.611333,3.424812,5.493390,0.453869,-14.072813
28081,-0.086039,-4.530020,-15.950516,-1.039653,-3.554509,4.487469,-23.190852,-11.895057,-16.086559,-11.290657,...,-27.147773,-23.754872,-3.630341,-1.783608,-1.485193,0.315449,-20.042137,5.409822,0.690741,3.733622

In [105]:
X34mean = df['x34'].mean()
df['x34'] = df['x34'].fillna(X34mean)

In [106]:
df[df.x35.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
14416,-0.399373,-3.160650,-15.437199,-2.412217,17.797917,8.346186,-22.444527,27.692261,1.303248,6.033774,...,17.378383,-31.224377,1.920998,0.260918,-5.730850,-0.083402,-33.159760,1.724370,-0.017652,-12.002704
19847,-0.325190,8.444185,19.058319,9.079944,-2.758887,11.335058,27.709364,29.818332,-1.820615,-3.747431,...,1.434731,20.200570,6.179586,0.281087,-1.605603,0.409985,-10.794291,-1.434084,-1.139711,-17.729032
25264,-0.017332,-3.586659,-6.703598,10.198560,-4.848450,-4.874768,-9.746528,-25.142513,6.953528,-0.145205,...,-2.184705,34.622013,5.466543,1.085035,4.907495,-0.205730,-21.455939,1.834891,-0.270602,6.250947
25286,-0.498620,-7.877283,-15.120576,2.830376,-1.766641,9.620148,-21.984181,-12.049445,-8.843414,-2.866796,...,6.127872,-28.304215,-1.220911,1.771169,2.085829,0.247980,10.239576,-2.817994,-1.752226,-6.330729
25839,0.728285,-8.486088,19.590821,-4.855069,3.404571,-16.253270,28.483582,-0.822349,-8.867138,5.887848,...,-0.076179,9.321687,7.546411,-0.256128,2.387657,-0.164808,17.013414,2.559383,-2.846207,-12.253896
35386,-0.216793,2.732010,23.978557,-9.951723,-1.961566,-3.425405,34.863020,-28.619274,1.514144,18.766143,...,-14.408819,28.778991,5.765884,1.130369,1.092543,1.169259,25.981893,-2.353513,-0.236506,10.006870
38488,0.201322,1.405612,-3.391294,-0.957816,6.112124,-7.843528,-4.930687,-19.806895,-9.461451,-1.030489,...,-28.984816,9.078117,-5.356490,-3.654206,4.343765,0.052596,-39.982963,-2.995453,0.626146,14.507389

In [107]:
X35mean = df['x35'].mean()
df['x35'] = df['x35'].fillna(X35mean)

In [108]:
df[df.x36.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
5262,-0.847320,4.791516,9.895755,-10.110230,-0.119687,5.185124,14.387684,-30.190718,-0.750176,5.732610,...,-10.846845,30.442974,-4.090708,-0.283897,1.377501,0.386416,-66.185924,0.676779,0.719164,-17.562971
6335,0.245023,1.655565,10.275922,4.914117,-1.903144,-2.374319,14.940418,-9.648123,0.874487,-4.704551,...,-23.200793,37.984755,-0.929453,1.087670,0.489161,-0.097120,8.446055,4.793385,0.223966,33.559640
8670,-0.616842,5.779704,2.715480,2.845271,-9.466576,2.711088,3.948104,-16.701870,-17.105780,-0.829884,...,-4.561319,9.222818,-2.550433,2.116302,-11.620837,0.070438,-22.112022,3.481859,0.340924,-4.385719
10192,0.269173,-1.592375,-16.607794,4.837451,1.069532,-6.589191,-24.146484,-37.453037,-4.478614,4.393652,...,34.804866,20.996385,-14.309137,0.368170,11.849812,0.690637,-41.191708,2.728663,0.730694,15.959848
17819,0.489494,12.599355,-5.887138,1.296626,7.634230,0.723438,-8.559457,12.826225,0.061550,2.150450,...,4.546775,-13.609370,3.525621,-0.433215,-5.523300,0.387297,-45.540754,-3.622930,2.848881,-14.904005
22006,0.066124,0.805736,14.157702,-11.391913,4.131233,4.335108,20.584234,-29.787645,-8.281904,8.368296,...,-4.690074,20.418237,-0.054917,1.718727,-6.799813,0.382993,-32.304567,6.709085,-0.598504,-13.180474
26605,0.489355,-7.703429,10.010861,-3.961302,10.767821,7.992770,14.555040,58.817716,-13.428958,-1.744682,...,19.388734,-1.978345,-3.849659,1.021933,6.448880,0.701340,-74.425304,-5.094649,1.524959,-8.361994
28528,0.202907,4.522180,-1.190227,8.550533,1.117638,-2.804850,-1.730501,-9.550129,-4.892251,-4.229309,...,-3.645615,4.543980,-5.326034,0.225574,1.821683,-0.414050,-20.206605,-0.132968,-1.709824,-0.220623
37491,-0.194734,8.573624,-18.024247,6.326774,2.317770,10.595451,-26.205901,-55.886295,-0.585232,-1.315948,...,-7.587005,-19.186316,-11.010940,0.629576,-0.200189,0.086244,-62.652716,-2.966775,-1.302574,-43.317537
38254,0.169951,9.067322,7.892055,9.955675,-0.657557,-3.311559,11.474455,13.214528,-1.259140,-5.526508,...,2.535128,0.233767,4.654305,0.521448,-6.628223,-0.166367,-26.129336,-4.184380,0.395415,-23.064054

In [109]:
X36mean = df['x36'].mean()
df['x36'] = df['x36'].fillna(X36mean)

In [110]:
df[df.x37.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
16094,0.215787,6.196603,-18.866967,-3.656699,-1.569939,6.937211,-27.431152,23.865383,11.560853,-2.123686,...,28.790868,-6.376034,-9.986722,0.985514,-2.104880,-0.011938,-54.956125,-0.239318,0.210179,18.389890
20093,-0.585556,1.104791,-13.581500,5.178984,5.943853,-5.083363,-19.746480,21.329397,1.501757,-9.935128,...,-12.729563,-3.599683,8.582280,-0.057298,-5.647977,0.418970,5.443976,0.601978,-1.057583,8.581827
23563,-0.273604,-9.118521,14.033596,1.973395,3.547352,-0.675843,20.403794,-97.545296,-23.571517,-3.996975,...,-11.404032,55.647115,-0.193515,-0.703034,5.768124,0.073453,83.767200,1.148688,2.443150,3.748136
25664,0.993153,7.849276,2.247457,13.605455,8.701200,0.013390,3.267633,12.192256,6.546145,-0.933492,...,-5.149787,11.208167,-0.477364,1.204368,2.317886,-0.650977,5.090421,-16.645355,0.981883,29.762480
36639,0.514706,-5.037639,13.941686,-4.153857,4.657376,6.307497,20.270164,-22.839131,-14.835688,-4.507357,...,10.961828,16.482052,-5.127355,-0.331251,3.594536,-0.323795,1.590559,-1.852424,-1.690936,-11.485287
39971,-0.484285,-2.355493,0.426684,8.615683,6.953455,15.912097,0.620367,14.423536,-6.799821,-11.285372,...,-1.495509,-16.379263,9.678255,1.213855,5.518131,0.050803,50.942827,7.284607,-3.254093,7.000519

In [111]:
X37mean = df['x37'].mean()
df['x37'] = df['x37'].fillna(X37mean)

In [112]:
df[df.x38.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
3846,0.636788,-2.017937,-17.150360,-23.949792,-4.233618,-10.853055,-24.935334,1.166430,0.462253,4.398373,...,-4.823369,7.185906,-3.146914,-1.502665,8.290276,-0.166109,7.966258,-4.151176,2.830554,24.870621
17108,-0.514285,12.385222,-22.883999,3.986968,-7.579869,-0.162371,-33.271615,-69.386634,-1.049265,-5.047256,...,-7.839156,3.169745,-8.559494,-1.394389,-1.385364,-0.162934,-0.572887,-2.328737,1.244382,-11.059149
17552,-0.341284,9.451511,-24.940806,-1.614173,-5.071143,-5.166988,-36.262058,9.935029,-13.506262,2.028049,...,4.301679,-11.225168,-3.786656,-0.273548,1.095412,0.447343,-31.441838,0.733490,3.645196,-2.708739
21777,0.064095,-1.773630,1.585186,-1.365794,9.613089,10.928269,2.304741,8.468561,1.203301,-6.715853,...,12.763728,-4.898396,4.682302,0.609851,-3.688368,0.477948,44.682879,5.421203,-0.925407,6.539581
22137,0.433885,-1.320913,6.926570,13.111097,-2.024882,-5.534375,10.070712,1.180145,-22.216487,0.343142,...,20.472811,-14.111544,5.407394,-1.514400,-2.199329,-0.038918,55.438590,-6.409438,-3.676317,-1.169333
35622,1.049189,-0.706301,-2.481181,6.962410,4.340535,1.165974,-3.607450,13.084316,4.136395,-13.668255,...,-13.595349,0.544037,-5.568173,0.243004,-1.311245,0.676907,-62.022299,3.402598,0.153993,-2.516312
36214,0.136357,3.230926,-20.780349,-1.810520,0.517741,7.652614,-30.213066,8.344968,-11.429912,0.028391,...,-20.151522,9.108583,-3.313281,0.462199,2.582710,-0.181470,-20.989993,-5.519764,4.286114,24.904345

In [113]:
X38mean = df['x38'].mean()
df['x38'] = df['x38'].fillna(X38mean)

In [114]:
df[df.x39.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
16,-0.080002,-3.996057,12.610601,2.699778,3.305612,14.143028,18.334866,5.918937,6.168532,4.562688,...,4.160472,0.728321,0.795320,-1.993936,-8.423694,-0.112500,-0.445456,8.485323,-0.620149,0.531935
9268,1.053192,9.647869,-12.485177,3.463141,-19.435812,-6.093937,-18.152510,-28.285920,2.208909,-8.065352,...,-1.175914,6.331911,-8.094475,-0.320503,-1.884225,0.182998,-7.135580,7.989577,-0.498023,3.203126
9316,-0.108282,-5.146695,-16.223734,1.292472,1.802176,-5.059746,-23.588090,8.401769,17.106633,-0.413409,...,6.150743,-8.351801,0.840133,-1.239931,-0.012127,-0.206861,22.502886,1.912724,3.737906,12.174225
10476,0.262150,1.813446,-6.922057,7.460793,9.491770,2.960379,-10.064151,-52.207283,14.557908,3.407009,...,-28.349399,24.335920,-4.180457,-0.470512,-8.514626,-0.635695,-8.287375,-0.927576,-2.122376,13.172259
14307,-0.144874,-9.016910,-5.146654,-4.603383,-0.500101,-2.839276,-7.482849,-29.802878,-9.263695,-5.082660,...,-1.402863,34.856125,-11.606748,1.557804,-8.764081,-0.184257,-20.063812,-0.511902,0.701231,16.303593
18063,0.297724,4.351172,24.103489,-0.902837,8.495825,3.678302,35.044662,-8.275795,0.330607,4.383331,...,-2.793886,10.952601,6.457076,0.408052,5.885659,-0.444043,48.941430,-0.639129,0.288318,-4.029788
19074,0.611687,1.347767,9.676274,4.206205,-2.632509,6.405889,14.068576,5.110087,-6.932786,-9.017737,...,5.385610,31.574956,3.685989,-0.745554,0.807886,0.641102,24.048025,-1.604325,1.466907,19.444354
25534,0.432266,8.709239,1.552213,-0.130690,-5.721504,14.655209,2.256802,-5.099105,0.040991,-1.323484,...,-20.605737,9.692855,1.333547,0.085951,3.350339,-0.201343,-69.025479,4.242314,-3.886487,-4.763224
27672,-0.533208,9.834140,-7.125335,7.848300,10.163456,-4.323312,-10.359702,-0.715254,-13.640333,-2.531422,...,-2.935814,8.224330,-3.672283,-2.003145,-0.160266,0.225616,-7.886708,-3.199904,0.521717,7.656024
29652,0.763643,-11.301337,-1.381072,8.720167,-1.358833,2.317204,-2.007974,42.137449,4.800872,0.854555,...,25.705214,3.157820,0.463478,0.569447,3.931203,-0.091427,-3.903425,4.523400,2.441429,6.289020
39731,0.118695,-11.764550,5.692233,-26.293365,5.488238,-1.505307,8.276079,-38.949567,-17.221554,4.361646,...,-5.662953,15.461278,-7.200610,-0.246226,3.111564,0.022221,2.256452,-2.396175,-3.368245,1.350753

In [115]:
X39mean = df['x39'].mean()
df['x39'] = df['x39'].fillna(X39mean)

In [116]:
df[df.x40.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
437,0.365192,3.879024,8.794182,2.775357,1.397091,10.866090,12.786080,-7.857713,15.561306,2.123218,...,NaN,11.898467,-1.470849,0.923427,-0.034080,-0.259296,-23.835802,-8.730397,0.758020,-9.320593
9156,0.703037,2.394103,4.303371,-9.645739,-4.964873,-0.518558,6.256777,-2.907388,16.505947,3.626709,...,NaN,-12.076552,-3.124389,-0.159335,0.757402,-0.010535,-0.949543,4.450282,-4.702713,-10.136817
15379,0.892063,-2.894879,1.470257,4.528527,-1.641540,7.031768,2.137643,-44.895930,-3.974604,7.507552,...,NaN,25.303924,-0.168619,1.507324,-1.390961,-0.231380,27.796867,-2.885340,2.610925,4.265526
20220,-0.096014,-0.508989,7.347254,-2.609074,-1.482797,-8.382781,10.682356,7.400388,4.493540,-11.907742,...,NaN,-8.153690,-3.402474,-0.784719,4.565342,0.584350,-31.779823,7.461049,-0.160214,-4.269023
29995,-0.763138,9.248775,0.041168,8.367981,2.471505,1.834753,0.059855,0.095981,-3.831219,-0.481571,...,NaN,22.877332,6.919826,-1.417542,5.447571,0.075314,35.508596,-3.530861,2.189590,20.557314
32305,-0.221473,0.828993,-3.727737,-2.390823,-1.803373,-0.967600,-5.419849,49.957242,14.539396,4.930287,...,NaN,-6.456858,-4.483890,-0.887714,-0.359206,-0.296651,-91.550715,0.200794,4.234470,-11.079693
33403,0.134717,-3.437987,11.282956,-7.930074,2.390381,-6.924888,16.404570,-38.440315,-8.265803,9.878967,...,NaN,13.741746,-1.012740,2.601363,0.115308,-0.120424,45.811475,0.575838,-1.041500,11.509479
38393,0.536455,-10.358017,-8.466305,0.583202,7.571502,-12.930384,-12.309371,-5.734031,-13.109378,-7.480835,...,NaN,25.933854,-4.528673,1.400236,-0.552368,0.038201,-7.345895,-2.461669,3.906145,29.531204

In [117]:
X40mean = df['x40'].mean()
df['x40'] = df['x40'].fillna(X40mean)

In [118]:
df[df.x41.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
6150,-0.336030,-13.328212,-21.504918,10.885016,0.722840,-0.825255,-31.266534,24.573698,10.115397,1.694391,...,3.264376,NaN,-3.596261,-4.990329,1.629460,0.700704,-28.799620,2.498626,4.438151,-7.324459
14794,-0.223080,-1.933165,-27.213188,3.593593,-3.006815,-8.741365,-39.565931,-20.091592,1.985295,8.161275,...,28.879173,NaN,-8.812437,-0.050206,-0.428004,-0.299324,21.293809,5.540799,0.476421,39.925086
17997,-0.044495,5.368418,-9.120387,0.213457,-3.902121,-9.557540,-13.260358,-15.117382,8.582972,0.464724,...,-5.807480,NaN,-1.999459,0.722503,1.261512,-0.522229,-30.785871,0.154426,1.638291,1.587925
29973,0.048728,1.733857,11.841802,4.850667,10.398729,-15.751714,17.217090,-20.918177,-16.794317,-3.825052,...,-11.913803,NaN,-5.605817,0.539140,-1.225943,-0.565342,-13.857133,6.608814,-1.659302,-6.169520
34853,-0.042474,0.952161,1.281720,3.766746,-0.263337,-2.261944,1.863525,22.721669,-4.405104,-3.449273,...,-14.129101,NaN,6.593719,-0.741313,1.546871,0.378169,-3.378742,1.921241,-0.622381,8.582437
37171,-0.808841,0.541762,1.340401,-7.037720,7.239433,1.981711,1.948843,16.136898,20.501456,-9.434892,...,-8.239486,NaN,9.485219,0.318916,-1.380140,-0.369426,61.458294,5.947729,-0.725442,10.721528
38505,0.140536,5.267820,5.656602,2.644636,1.808980,-1.779763,8.224274,24.594187,7.022540,-4.217975,...,8.438502,NaN,-3.553385,-1.614507,-7.949598,-0.244165,-55.382733,-5.042932,-1.991585,5.459969

In [119]:
X41mean = df['x41'].mean()
df['x41'] = df['x41'].fillna(X41mean)

In [120]:
df[df.x42.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
176,-0.478195,-6.721827,-15.164784,3.914474,3.411644,16.045840,-22.048457,-18.692620,-14.678598,0.727056,...,-6.201832,-8.298007,NaN,-1.282679,-3.232978,-0.433443,24.970770,-1.490086,-0.459047,2.014385
3171,-0.408392,-7.838919,4.739126,2.685655,9.117706,-18.415246,6.890333,-13.399355,3.254762,1.249281,...,-3.349403,26.098471,NaN,-1.247016,-6.924580,-0.388766,35.028899,0.901137,3.746859,15.550707
7114,-0.569018,7.135016,-3.564319,-10.223572,-1.513205,1.586788,-5.182252,23.569107,-3.759515,-7.195894,...,22.567825,-16.844849,NaN,1.391065,7.536059,-0.562879,46.561746,-1.460576,-1.170577,11.522002
8368,0.004230,0.001380,-21.385907,6.703077,-3.663886,7.816167,-31.093502,-35.025878,-1.401384,1.070728,...,-11.862521,-16.759113,NaN,3.590034,5.971320,-0.350113,14.851682,-1.864360,-0.434633,13.350520
11245,0.644469,1.054595,-17.682362,-16.452683,-0.553720,-15.670416,-25.708826,-8.804361,-8.366640,2.399687,...,1.544703,0.782778,NaN,1.893268,-2.519923,-0.591203,-20.102160,8.495521,1.563578,6.106311
13145,-0.087218,-0.315323,-15.082764,-2.772441,-2.389337,3.186963,-21.929206,30.269715,7.015386,-7.966058,...,-7.372351,-23.490060,NaN,2.438982,-0.634440,-0.110784,-0.276545,2.954915,2.048051,12.588503
13298,-0.125364,7.873809,-11.252392,0.918962,4.167068,7.222105,-16.360132,12.627026,-12.701469,-0.872158,...,22.594414,-23.490141,NaN,2.447552,-5.357878,0.814926,0.465580,6.805250,-0.080027,-3.902162
14102,0.182262,5.852633,-14.935655,-14.667187,0.140626,13.420456,-21.715320,0.882106,-4.163034,-14.002301,...,-14.794815,9.539943,NaN,0.570436,-3.990004,0.188947,37.472721,-2.813572,3.089813,23.719406
20395,0.170305,-4.198331,-8.119965,-0.829796,3.709032,0.780171,-11.805820,-51.039552,-13.561959,6.092688,...,-14.351792,13.970397,NaN,-2.211455,-6.732609,0.124265,61.370206,6.404483,-0.601910,7.171715
21328,0.251165,9.912054,1.092577,5.545670,-12.160556,7.491755,1.588525,-36.797867,-1.448527,-0.845081,...,-23.482111,34.303050,NaN,-0.167340,5.074467,-0.313013,-17.169255,2.883555,0.198834,22.203620
22381,0.607679,12.762317,-13.404263,-9.869715,-8.158299,-9.819848,-19.488792,-12.264021,9.156309,-11.309189,...,-28.089539,-2.172404,NaN,-1.398671,-3.400888,0.468587,-3.597066,-1.001813,1.175035,19.059031
24013,-0.199419,8.849620,16.569342,-1.875279,4.140412,1.416011,24.090579,-24.422026,17.961457,11.544245,...,-25.019239,18.182498,NaN,0.665273,-9.448675,-0.131027,43.762792,-5.334633,-4.610517,-7.914573
25363,0.201700,11.427686,-8.334164,-12.850401,5.665724,5.141074,-12.117248,51.285749,-12.840919,2.590257,...,1.088064,-13.110060,NaN,-1.384359,-2.371791,-0.041826,-15.270665,0.911551,0.224330,28.425527
32326,0.628471,5.371227,-19.625945,-7.125862,1.408904,-2.311773,-28.534650,-103.753931,-2.523782,4.183566,...,-1.673020,49.626386,NaN,0.277520,4.900782,-0.126447,-36.616872,2.863446,1.028220,-10.382043
34275,0.060243,9.020194,2.619788,-9.793713,-7.763385,-12.412165,3.808975,19.070942,-1.546465,3.904895,...,-4.754934,1.037275,NaN,-0.947952,-1.941238,-0.266348,-32.310800,5.755461,-0.942875,-5.216052

In [121]:
X42mean = df['x42'].mean()
df['x42'] = df['x42'].fillna(X42mean)

In [122]:
df[df.x43.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
879,0.344249,9.574485,-6.190021,2.753796,-9.473160,-10.528537,-8.999825,17.315973,-16.564721,4.713151,...,1.489300,-2.952096,1.023792,NaN,-2.288455,-0.377789,-21.635364,4.115620,2.399953,2.032534
15471,0.092203,-1.559391,-4.399987,-7.226282,9.930345,-4.524335,-6.397251,-3.777413,-7.972310,-0.915081,...,0.909072,-19.613139,-0.585713,NaN,1.648396,0.076606,-17.627590,3.169974,-2.138679,-22.576878
17227,-0.341932,-8.411488,-2.523392,11.891238,-10.369378,4.170640,-3.668823,16.481678,9.135214,2.275513,...,-8.846763,10.799868,-3.349097,NaN,1.927037,0.024320,-34.756804,2.110009,-0.267132,17.857122
19405,-0.594582,1.477503,5.790700,-10.554199,1.943360,-5.874398,8.419242,26.957924,1.835322,2.946399,...,-17.556905,3.419904,1.767408,NaN,-0.804533,0.018038,-8.669079,-4.905780,-2.399100,4.645059
20489,-0.610018,2.486279,8.322254,-8.638627,-4.307173,-9.565712,12.099932,34.561824,1.161393,-9.115231,...,6.782539,12.401216,0.024279,NaN,0.325037,0.208678,-9.737231,2.489677,0.347539,14.983435
21747,0.016846,-1.888094,-12.013903,5.952618,-7.876948,9.693125,-17.467312,-10.469059,5.581973,-8.744084,...,-28.246014,-28.658441,-6.269380,NaN,1.337726,0.303452,33.983247,0.778445,0.694963,-2.614350
23089,0.262215,0.660787,-5.050786,18.766009,4.332599,11.875519,-7.343463,-23.325341,9.410362,-0.788074,...,-32.391307,-5.873973,-4.781750,NaN,1.598297,0.096927,2.857734,5.881564,-0.892219,19.963903
33535,-0.151275,0.478564,1.872506,-9.594180,4.598919,15.410197,2.722483,43.890103,0.881435,-3.714164,...,-6.471322,2.786155,9.942875,NaN,11.420328,-0.610258,-41.265129,-2.841637,-2.430241,20.458361

In [123]:
X43mean = df['x43'].mean()
df['x43'] = df['x43'].fillna(X43mean)

In [124]:
df[df.x44.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
10774,0.109028,-0.427683,0.888844,-4.210199,-8.225736,8.071747,1.292312,13.311616,-5.469643,-0.935904,...,19.163134,-7.555754,-3.109462,1.072755,NaN,-0.047079,-21.097986,7.900344,-0.687546,0.941129
20836,0.222625,-5.523281,-5.337231,-5.706568,11.130830,10.472277,-7.759932,18.884745,4.514229,-9.182591,...,0.634514,-12.416454,6.916485,-0.765754,NaN,-0.626679,36.303247,2.140877,-1.116113,2.441332
34812,-0.200585,-2.794487,-11.322470,-7.284088,-3.332011,-10.764378,-16.462021,-42.308816,-5.088984,-10.769981,...,-10.733453,1.760792,-8.180637,-0.532571,NaN,0.289109,1.789848,-4.227559,-2.836849,4.038609

In [125]:
X44mean = df['x44'].mean()
df['x44'] = df['x44'].fillna(X44mean)

In [126]:
df[df.x45.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
4266,-0.557199,-6.925351,-10.103099,8.626165,-5.326997,-8.038755,-14.689147,-12.337394,-15.712595,7.781490,...,10.134818,31.348029,-6.534535,-1.564131,-7.779594,NaN,-46.536306,10.987367,2.921552,10.184574
19363,-0.543241,-0.715072,-3.539131,6.729807,-2.981873,18.508079,-5.145630,21.511902,-11.657148,-5.183158,...,7.171934,-29.369371,4.143794,-0.801839,2.359192,NaN,1.680970,-3.831969,-3.832406,-8.189690
19618,0.426868,-14.813121,-10.787977,-2.101914,-7.358982,5.608836,-15.684908,0.070282,-0.401704,-11.030899,...,-39.332436,-3.033954,-3.406416,1.340102,10.527763,NaN,-0.446119,-6.543263,0.442237,36.524691
39133,-0.095398,-9.697760,-5.329847,-0.011274,3.583647,1.431495,-7.749196,7.979487,1.994824,6.586985,...,9.633239,-0.553143,-0.797442,0.676613,-7.010775,NaN,-28.301166,5.229062,2.991915,-12.751381

In [127]:
X45mean = df['x45'].mean()
df['x45'] = df['x45'].fillna(X45mean)

In [128]:
df[df.x46.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
6337,0.399222,-1.376901,9.067140,10.170435,7.885800,11.093964,13.182940,41.888000,-7.104086,-8.488659,...,33.746594,-7.887341,-7.393743,1.362466,-1.452324,-0.548394,NaN,9.839836,-1.333336,-18.098688
12914,0.056622,-2.793444,8.873503,-2.613840,-0.646611,-5.531871,12.901406,-27.505396,3.090631,-5.283227,...,15.874580,4.968462,0.870035,-0.626012,7.232067,-0.097663,NaN,3.346791,0.011749,-25.331020
20949,-0.679603,0.159430,-1.323181,2.745183,1.396686,10.543891,-1.923805,5.820900,-11.225989,-3.736471,...,-18.103036,5.979272,-5.542087,0.116425,3.632729,-0.022454,NaN,-3.776469,1.879411,13.218847
24128,-0.282070,0.358847,-11.238007,0.652335,5.782241,-14.426988,-16.339218,4.610649,-8.058337,13.312803,...,22.560456,-6.114299,-13.270190,2.779277,0.040482,0.129223,NaN,4.993334,1.654455,-10.664103
25547,0.045479,1.125288,-13.902921,-5.353646,-10.105736,-1.946810,-20.213802,-15.218781,12.636163,10.063526,...,32.623292,28.694412,-5.840196,-0.681724,-2.225584,-0.021926,NaN,6.213728,1.002403,11.783248
26947,-0.535929,1.282079,-10.195029,-3.020579,-12.900266,3.838402,-14.822806,-61.816852,1.948278,-5.091567,...,-35.594714,29.777058,-7.637709,0.090808,-9.760935,0.392108,NaN,1.280338,-4.319506,22.037433
32889,0.166872,5.281928,-3.482370,5.509571,-2.421724,8.003706,-5.063105,27.040485,8.495376,-6.794139,...,-0.717451,5.389486,-5.568193,1.616506,-0.503112,0.503132,NaN,-3.815454,2.208609,13.004520

In [129]:
X46mean = df['x46'].mean()
df['x46'] = df['x46'].fillna(X46mean)

In [130]:
df[df.x47.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
10428,0.586417,6.205210,-15.204030,3.487679,-8.718124,7.395227,-22.105518,33.712120,-3.662548,1.464405,...,16.543692,-18.787529,-4.285622,0.883047,1.068795,-0.621042,-72.370768,NaN,2.244406,-15.957138
11735,-0.167893,0.676634,6.067071,1.190937,-4.153683,12.533595,8.821065,34.567573,3.863377,-4.314187,...,41.021033,2.275071,3.067613,-1.508622,0.714247,0.380947,-18.586692,NaN,2.991162,-13.917819
19849,-0.088663,-5.340698,-30.715367,13.918038,-6.444800,-1.803833,-44.657836,-15.190739,0.365751,-4.630004,...,16.366874,-7.202249,-3.766701,1.398182,2.471006,-0.063250,0.468033,NaN,2.834777,26.265538
38829,-0.135847,-8.702232,16.259209,-1.733463,-2.060558,-17.494272,23.639668,31.694563,3.952662,-0.505370,...,5.958506,19.996860,4.441465,0.709273,6.953686,0.215636,-41.529115,NaN,-0.912732,-12.335061

In [131]:
X47mean = df['x47'].mean()
df['x47'] = df['x47'].fillna(X47mean)

In [132]:
df[df.x48.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
7639,0.205435,5.609298,-9.493754,-4.319544,0.199473,-0.240697,-13.803205,44.925152,6.479611,5.582882,...,-15.948049,-15.982176,4.996145,-0.724870,1.698208,0.195062,30.573088,-8.480416,NaN,13.181579
19606,0.443298,-4.056405,-13.162557,4.078415,-4.746388,-1.833726,-19.137368,-17.487569,1.408640,0.576975,...,-0.909352,5.325814,-3.243704,-1.723375,-0.516343,0.448476,28.129233,-2.042521,NaN,17.652575
28429,0.373614,-2.637583,-9.939582,12.810239,3.000629,3.047664,-14.451406,-11.832038,8.492591,10.979829,...,-24.596440,0.029134,-5.026096,-0.418491,-2.485887,0.221412,2.572329,-1.804573,NaN,25.918186
29546,0.507755,-4.151167,24.153121,8.442898,-1.811775,4.464628,35.116822,-5.346602,-8.373867,-1.661163,...,1.368002,38.648554,0.654860,-0.994048,-2.739130,0.096155,-14.994982,0.830516,NaN,-7.578567
29959,0.031296,-2.859436,-11.629156,8.275609,-2.104092,5.959446,-16.907919,8.296320,4.054802,-1.178469,...,8.112014,-27.001133,3.548240,-0.985215,-2.140894,-0.868068,2.928384,2.680655,NaN,-16.720215

In [133]:
X48mean = df['x48'].mean()
df['x48'] = df['x48'].fillna(X48mean)

In [134]:
df[df.x49.isnull()]

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49
202,-0.033666,3.619146,-17.619922,6.415630,4.800279,-0.067147,-25.618042,14.204170,19.893352,-7.089081,...,-10.748451,-28.938351,-3.390374,1.468866,-6.802180,-0.037301,-4.211652,0.753212,1.129832,NaN
1722,0.319747,-0.933951,20.190411,-0.290101,-7.438682,1.293854,29.355341,15.017895,-3.228918,-12.972986,...,-15.641233,21.228092,7.583885,3.054190,6.113549,0.186999,30.377567,8.121702,-2.274548,NaN
6863,-0.229236,-4.345110,2.753285,5.205662,-6.210818,-15.244682,4.003070,72.136244,11.721121,11.499953,...,15.544071,-29.046690,5.327264,-0.722525,1.234350,-0.410915,-0.390711,1.949245,-1.297274,NaN
9115,-0.066091,4.743803,13.664305,-9.599818,-6.018092,3.162781,19.866872,-25.802297,11.624999,9.884795,...,-11.484565,20.727132,3.582033,-0.538530,4.972585,-0.174104,-2.763061,-2.501300,-3.234020,NaN
16024,0.086376,-5.212479,2.472887,-17.018599,5.122562,-9.679805,3.595392,-21.596739,13.369188,4.132841,...,-7.171629,32.697108,4.972959,-0.274360,4.085004,0.119921,-45.206598,-5.613318,-3.573795,NaN
21460,0.036625,-6.487325,20.236683,-7.346954,-3.240451,7.244555,29.422617,-4.449586,21.036866,0.738494,...,14.805419,18.700884,2.052934,-1.926598,1.735832,0.037890,-26.162642,-5.435551,-1.672656,NaN
24305,0.093015,-2.804357,-30.060086,21.074477,-6.888410,-3.508682,-43.705107,-25.290346,11.780193,-12.130611,...,-17.521982,-30.240431,-0.866947,1.255140,-4.076210,0.421328,22.022321,1.640228,-0.636492,NaN
27833,0.262120,-6.071872,-8.297080,-7.294341,3.396619,2.592629,-12.063331,-13.842421,-2.603635,3.586046,...,-10.603373,0.313886,1.414876,2.505729,5.211522,-0.274072,50.864233,8.091351,2.476101,NaN
28305,-0.409774,8.017070,6.761643,-7.090328,3.629280,11.614336,9.830921,-0.511234,7.883856,-0.686752,...,-13.235421,7.277848,2.918863,-1.251781,3.432052,0.091518,-1.287950,2.148397,-0.806016,NaN
29138,0.275531,-3.509939,22.025363,-9.415082,-1.829508,-8.952550,32.023223,10.571725,0.849820,1.391904,...,18.925860,17.291285,-2.143023,0.837757,-0.088835,-0.134970,-58.531185,8.213442,-0.290173,NaN
29257,-0.015817,-9.125660,-0.635712,8.418250,1.903652,-7.278286,-0.924277,-9.670073,-1.632518,-6.991204,...,6.025899,8.026070,3.835848,-0.309805,0.966518,-0.444599,-16.947563,-2.411694,0.309507,NaN
34928,-0.426259,9.094044,-7.439909,0.546973,-2.960951,-12.636301,-10.817069,-43.254316,4.053134,-0.794167,...,10.468189,13.976692,-11.999919,0.353827,-4.363258,0.998219,-61.146088,-6.938929,-0.035188,NaN
35280,0.220277,4.936860,7.999063,1.894542,5.355887,-2.578659,11.630037,23.944716,-6.583118,5.492909,...,6.752643,12.539814,0.667004,-1.419918,2.162745,0.196762,-78.653115,-2.800934,-0.129066,NaN

In [135]:
X49mean = df['x49'].mean()
df['x49'] = df['x49'].fillna(X49mean)

In [138]:
df[df.x1.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [139]:
df[df.x2.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [140]:
df[df.x3.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [141]:
df[df.x4.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [142]:
df[df.x5.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [143]:
df[df.x6.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [144]:
df[df.x7.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [145]:
df[df.x8.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [146]:
df[df.x9.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [147]:
df[df.x10.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [148]:
df[df.x11.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [149]:
df[df.x12.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [150]:
df[df.x13.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [151]:
df[df.x14.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [152]:
df[df.x15.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [153]:
df[df.x16.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [154]:
df[df.x17.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [155]:
df[df.x18.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [156]:
df[df.x19.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [157]:
df[df.x20.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [158]:
df[df.x21.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [159]:
df[df.x22.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [160]:
df[df.x23.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [162]:
df[df.x25.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [163]:
df[df.x26.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [164]:
df[df.x27.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [165]:
df[df.x28.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [168]:
df[df.x31.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [169]:
df[df.x32.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [170]:
df[df.x33.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [171]:
df[df.x34.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [172]:
df[df.x35.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [173]:
df[df.x36.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [174]:
df[df.x37.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [175]:
df[df.x38.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [176]:
df[df.x39.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [177]:
df[df.x40.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [178]:
df[df.x41.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [179]:
df[df.x42.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [180]:
df[df.x43.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [181]:
df[df.x44.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [182]:
df[df.x45.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [183]:
df[df.x46.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [184]:
df[df.x47.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [185]:
df[df.x48.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [186]:
df[df.x49.isnull()]

Empty DataFrame
Columns: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x25, x26, x27, x28, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x24_Missing, x24_america, x24_asia, x24_euorpe, x29_Apr, x29_Aug, x29_Dev, x29_Feb, x29_January, x29_July, x29_Jun, x29_Mar, x29_May, x29_Missing, x29_Nov, x29_Oct, x29_sept., x30_Missing, x30_friday, x30_monday, x30_thurday, x30_tuesday, x30_wednesday]
Index: []

[0 rows x 70 columns]

In [187]:
df

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x29_Missing,x29_Nov,x29_Oct,x29_sept.,x30_Missing,x30_friday,x30_monday,x30_thurday,x30_tuesday,x30_wednesday
0,-0.522582,1.285266,-3.211278,6.435478,-3.355995,-6.222153,-4.668957,26.648275,-9.493768,-15.919583,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,-0.327133,-2.874201,-8.628286,-4.543222,-0.687731,-0.306087,-12.544880,9.719749,-14.072453,3.763146,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,-0.173731,-11.401446,7.633143,7.298406,-5.554917,-17.192158,11.098016,-41.911009,12.719480,-7.320119,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,-0.130836,4.716583,-18.537297,-2.334537,-3.697804,-0.162074,-26.951837,-21.238950,3.145513,0.661810,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.035572,-0.141469,7.792464,-4.398339,0.823660,-0.665133,11.329657,-12.837209,-5.064350,-3.699563,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,0.171480,1.376789,-12.157398,0.552619,-2.565093,-5.471192,-17.675943,-28.142754,-2.641366,-10.103862,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,0.272986,6.858258,32.283563,2.005428,-10.277287,-8.216530,46.937875,-2.531384,12.522623,6.830416,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,-0.521643,2.175613,10.731249,-2.015805,-6.392855,-12.386190,15.602430,41.930868,-2.728404,3.964700,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8,-0.328042,0.982469,6.182135,1.817593,-6.348914,-2.574139,8.988360,-2.080090,-3.697630,-5.189804,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,0.247553,3.381052,-2.453479,0.724840,11.503477,-0.781279,-3.567174,-27.943328,-9.035508,0.339077,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,-0.210306,-0.239739,21.486137,2.689674,5.938704,0.598897,31.239229,12.752803,17.058996,-3.189227,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11,0.018683,7.213448,-16.039051,-2.629574,2.577776,-5.562803,-23.319575,-74.116006,4.679182,7.011748,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12,-0.155589,7.499254,4.404225,1.940473,-3.976658,-0.877287,6.403412,36.657849,-20.911237,0.310982,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13,0.308492,6.085123,13.575007,2.680646,13.255324,10.939647,19.737040,-6.006773,-10.978509,-16.667573,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
14,0.017013,-5.286507,2.904534,14.504134,12.433290,4.419134,4.222975,-14.994015,20.981186,14.610730,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,0.325367,4.976472,-17.348713,-10.847553,-8.040693,-6.887668,-25.223725,20.187760,-1.447577,-4.047585,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,-0.080002,-3.996057,12.610601,2.699778,3.305612,14.143028,18.334866,5.918937,6.168532,4.562688,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17,-0.586387,-2.072544,-16.544132,8.825365,4.443378,-2.954797,-24.053925,22.643515,2.421437,3.681146,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18,-0.641136,3.942238,-21.629201,-4.151271,-4.373297,-6.520598,-31.447233,-28.013929,0.908673,0.572782,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,-0.395920,-6.114338,-27.659525,-7.280915,3.290333,-0.129625,-40.214872,-56.110837,1.012466,-8.915614,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
20,-0.485172,-6.274926,-13.397973,7.412372,4.741546,-2.257849,-19.479646,-69.602706,-6.931137,-1.862582,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
21,0.333137,5.055409,-22.144757,6.594828,-2.446685,-7.432998,-32.196813,-2.200601,8.717481,5.350683,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22,0.069176,1.963769,-9.865067,1.911268,6.577322,11.358527,-14.343066,-41.113846,5.009580,3.401839,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
23,-0.535690,4.496029,-13.683126,-2.868913,0.008019,-10.080747,-19.894237,-49.020493,20.508301,-2.363934,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
24,-0.205164,2.881020,-15.141999,-3.989058,1.360720,6.134124,-22.015329,-26.604160,-4.852563,2.367048,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
25,0.315679,1.264338,-17.556936,8.578909,2.369908,-0.393344,-25.526466,-46.904039,6.444937,7.695141,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
26,-0.174720,1.170017,-30.098568,5.008290,-2.304848,2.927120,-43.761056,-8.250150,-6.584150,-0.389502,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
27,-0.030121,-0.851378,13.307987,3.040727,4.794204,8.139623,19.348813,-4.696286,-0.268660,-1.440509,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
28,-0.273166,-0.359987,-10.095182,0.270800,-1.502322,3.186647,-14.677635,-17.711317,8.841165,11.461115,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
29,0.633948,5.829540,1.671938,-6.954487,2.717792,4.093655,2.430872,-21.096040,-1.982551,-8.744463,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39970,-0.345707,1.874505,11.481731,-1.419576,-3.881407,-6.338819,16.693574,-5.461446,11.114898,0.250702,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39971,-0.484285,-2.355493,0.426684,8.615683,6.953455,15.912097,0.620367,14.423536,-6.799821,-11.285372,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39972,0.617314,-6.528528,6.686249,4.245257,0.890885,-9.714896,9.721304,49.016511,0.175033,8.311528,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39973,-0.023021,9.829396,12.652664,-1.338658,7.763766,-2.830804,18.396023,25.096030,1.403248,5.410180,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39974,-0.441850,6.157621,-15.157058,-7.306126,5.739133,12.688878,-22.037223,11.394979,13.332746,18.266126,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39975,-0.414301,6.179540,-8.622131,-12.537705,-11.231099,-5.788203,-12.535931,33.494801,7.928966,-3.953694,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39976,0.147412,-3.186033,1.543382,6.318377,-5.820981,-6.197991,2.243961,17.470111,15.491912,0.233058,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39977,-0.487199,7.994729,6.329232,-18.624770,-9.053370,-7.016100,9.202227,46.052530,-3.797160,-9.983223,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
39978,-0.126870,12.552517,10.988795,13.519183,-2.887894,-0.763106,15.976882,-19.859236,-6.464905,-2.112823,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
39979,-0.771296,9.709924,12.630820,-7.127235,-1.425308,-6.181039,18.364263,1.978891,-0.869998,-6.933248,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39980,0.481050,11.172939,12.414156,7.554250,-10.528428,14.491265,18.049250,-25.442062,-0.915246,-5.448341,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39981,-0.364731,-0.103428,17.144194,4.252807,-4.021256,-12.017106,24.926370,-11.969062,9.623548,-4.871103,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
39982,-0.484536,-1.800296,-13.999401,-6.691342,3.847907,4.085345,-20.354078,-2.304984,-5.929689,-3.272676,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
39983,-0.048548,1.795239,26.199540,18.135421,-3.720871,-8.291572,38.092163,61.887314,0.047673,-0.393987,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
39984,-0.965001,-8.864446,9.509522,5.876934,1.906224,5.122576,13.826131,-20.203413,0.745361,7.708034,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39985,-0.390439,0.314540,-2.011130,4.425452,6.069432,4.277965,-2.924032,15.693695,6.730816,-0.105810,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39986,0.289567,0.310706,-17.077116,-4.037626,6.891063,-10.752559,-24.828843,-32.081682,1.557999,-2.584129,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39987,0.254486,3.027239,-7.699231,-3.756585,0.346588,-4.585204,-11.194104,49.636567,-5.990366,-1.224033,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
39988,0.470924,-2.270800,-9.473906,-3.430523,-3.522805,-0.344620,-13.774347,-3.161366,1.507118,11.531317,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39989,-0.483412,5.852267,8.493909,-3.535045,2.422616,6.514695,12.349505,19.591069,-23.665163,1.002266,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39990,-0.000945,-10.874818,-0.382385,10.256470,7.668853,-1.136524,-0.555959,-38.796086,0.822667,-5.994408,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39991,0.031739,-10.006617,9.600395,0.793046,7.540454,7.460118,13.958253,10.162683,0.613728,2.916609,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39992,-0.355079,1.634255,11.913375,1.980916,1.731958,6.655533,17.321152,22.533829,-1.476207,5.498195,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
39993,-0.198622,7.057424,-8.935302,-1.632211,3.024415,-4.961673,-12.991258,-24.823632,-0.955407,0.303270,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39994,1.064998,-5.401655,-12.130966,-4.673106,-2.469352,-7.432861,-17.637514,-30.769847,12.831495,9.303452,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
39995,0.160820,0.451430,9.860918,12.392831,0.093869,4.961749,14.337034,-17.012005,-9.622135,5.244451,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39996,-0.093163,-0.801173,-8.605816,10.803393,3.389769,0.856064,-12.512210,16.033699,1.927985,0.531471,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39997,-0.612190,-9.270291,-6.780054,-5.740186,-1.310608,10.012555,-9.857689,-20.233148,0.848664,-4.812529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39998,-0.316799,3.766430,1.152464,-1.176831,-4.851525,-5.600819,1.675596,1.615355,-4.572450,-8.506975,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39999,-0.270424,-10.509561,-11.543818,10.027725,-4.708852,-2.675297,-16.783844,7.627271,-6.112762,10.661600,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [189]:
df.shape

(40000, 70)